#!/bin/sh 
# Copyright (C) 2009 OpenWrt.org

dlna_live=$(ps | grep twonkystarter | grep -v grep )
dlna_enabled=$(uci_get dlna main enabled)
samba_enable=$(uci_get system general enable)
chk_init=$(cat /tmp/initial_process)
                 
blkdev=`dirname $DEVPATH`
isUSB1=$(echo $DEVPATH | grep "2-1")
isUSB2=$(echo $DEVPATH | grep "1-1")

if [ `basename $blkdev` != "block" ]; then

    device=`basename $DEVPATH`
    case "$ACTION" in
	add)	

		if [ -n "$isUSB1" ]; then
			
			[ -e "/tmp/usb1_Dev" ] && exit 0
			echo "$device" > /tmp/usb1_Dev
			/bin/mount_usb1 &
						
		fi  
		
		if [ -n "$isUSB2" ]; then			
			
			[ -e "/tmp/usb2_Dev" ] && exit 0
			echo "$device" > /tmp/usb2_Dev
			/bin/mount_usb2 &
						
		fi

		;;
	remove)	
		#umount -f /dev/$device
		echo $device		
		;;
    esac	

fi
