#!/bin/sh

[ -f /etc/config/radvd ] && [ "$ACTION" == "start" ] && {
	IsIpv6Enable=$(uci get network.wan.ipv6)
	Is6rdEnable=$(uci get network.general.wan6rd_enable)
	
	[ "$IsIpv6Enable" == "1" -o "$Is6rdEnable" == "1" ] && {
		IsDHCPv6GivePD=$(uci get network.wan.dhcpv6pd)
		
		[ "$IsDHCPv6GivePD" == "0" ] && {
			# Static mode on LAN
			/etc/init.d/default_lan_radvd restart
		} || {
			# default to restart  radvd.sh  , because PPPoEv6 and DHCPv6 may not have this option.
			/etc/init.d/radvd restart
		}
	}
}
