#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=98

boot() {
	### NBG_5615/ZyXEL/Benny 2012/7/23 ###
	
	/sbin/configure_qos init
	
	config_load qos
	config_get enable general enable
	
	#guest_bandwidth_manage=$(uci_get wireless ra3 guest_bandwidth_enable)
	#guest_wlan_enable=$(uci_get wireless ra3 enable_guest_wlan)
	#wifi_hw_on=$(cat /tmp/wlan_on)
	#wifi_disabled=$(uci_get wieless ra0 disabled)     
	#wifi_ra3_disabled=$(uci_get wieless ra3 disabled)
	#wifi_sche=$(uci_get wifi_schedule wlan enabled)
			
	if [ "$enable" == "1" ]; then

		# disable hardware nat for obstacle
		#rmmod hw_nat

		/sbin/configure_qos start
		
	fi
	
}

start() {
	### NBG_5615/ZyXEL/Benny 2012/7/23 ###

	config_load qos
	config_get enable general enable

	##check hw_nat
	/sbin/chk_hwnat
	
	if [ "$enable" = "1" ]; then	
		/sbin/configure_qos start
	else
		/sbin/configure_qos stop
	fi

}

restart() {
	### NBG_5615/ZyXEL/Benny 2012/7/23 ###	

	config_load qos
	config_get enable general enable

	##check hw_nat
	/sbin/chk_hwnat
	
	if [ "$enable" = "1" ]; then
		/sbin/configure_qos start
	else
		/sbin/configure_qos stop
	fi
}

stop(){
	### NBG_5615/ZyXEL/Benny 2012/7/23 ###	

	/sbin/configure_qos stop

	##check hw_nat
	/sbin/chk_hwnat
}
