#!/bin/sh 

##check mode,if AP/UR,exit
local sys_mode=$(get_sys_mode)
[ "$sys_mode" == "2" -o "$sys_mode" == "3" ] && exit 0

boot() {
        . /etc/functions.sh
	include /lib/network

        scan_interfaces

        config_get WAN wan ifname
        config_get LAN lan ifname

        ## INSERT MODULES
        #insmod x_tables  2>&- >&-
        #insmod ip_tables  2>&- >&-
        #insmod ip6_tables  2>&- >&-

        #insmod nfnetlink  2>&- >&-
        #insmod nf_defrag_ipv4  2>&- >&-
        #insmod nf_conntrack  2>&- >&-
        #insmod nf_conntrack_ipv4  2>&- >&-
        #insmod nf_conntrack_ipv6 2>&- >&-
        #insmod nf_nat  2>&- >&-
        #insmod nf_conntrack_proto_gre  2>&- >&-
        #insmod nf_conntrack_proto_sctp  2>&- >&-
        #insmod nf_conntrack_netlink  2>&- >&-
        #insmod xt_connbytes  2>&- >&-
        #insmod xt_connmark  2>&- >&-
        #insmod xt_conntrack  2>&- >&-
        #insmod xt_helper  2>&- >&-
        #insmod xt_state  2>&- >&-
        #insmod xt_tcpudp  2>&- >&-
        #insmod iptable_filter  2>&- >&-
        #insmod iptable_mangle  2>&- >&-
        #insmod iptable_nat  2>&- >&-
        #insmod iptable_raw  2>&- >&-
        #insmod ipt_MASQUERADE  2>&- >&-
        #insmod ipt_REDIRECT  2>&- >&-
	#insmod ipt_REJECT  2>&- >&-
	#insmod ipt_PORTTRIGGER  2>&- >&-
	#insmod xt_webstr  2>&- >&-
	#insmod xt_mac  2>&- >&-
        #insmod xt_multiport  2>&- >&-
        #insmod xt_tcpmss  2>&- >&-
        #insmod ipt_LOG  2>&- >&-
        #insmod nf_conntrack_ftp  2>&- >&-
        #insmod nf_nat_ftp  2>&- >&-
        #insmod nf_conntrack_sip  2>&- >&-
        #insmod nf_nat_sip  2>&- >&-
        #insmod xt_string  2>&- >&-
        #insmod ipt_time  2>&- >&-
        #insmod xt_limit  2>&- >&-
	#insmod xt_pkttype  2>&- >&-
	#insmod xt_recent  2>&- >&-
	#insmod xt_connlimit  2>&- >&-

        ###IPv6
        #insmod ip6_queue 2>&- >&-
        #insmod ip6t_IMQ 2>&- >&-
        #insmod ip6t_REJECT 2>&- >&-
        #insmod ip6t_ROUTE 2>&- >&-
        #insmod ip6t_ah 2>&- >&-
        #insmod ip6t_eui64 2>&- >&-
        #insmod ip6t_mh 2>&- >&-
        #insmod ip6t_owner 2>&- >&-
        #insmod ip6table_filter 2>&- >&-
        #insmod ip6table_mangle 2>&- >&-
        #insmod ip6table_raw 2>&- >&-


        ## CLEAR TABLES
        #for T in filter nat; do
        #        iptables -t $T -F 2>&- >&-
        #        iptables -t $T -X 2>&- >&-
        #done

        #for T in filter ; do
        #        ip6tables -t $T -F 2>&- >&-
        #        ip6tables -t $T -X 2>&- >&-
        #done
        
		## firewall
        #iptables -N input_rule
        #iptables -N forwarding_rule_filter
        
        ## icmp filter
        #iptables -N input_icmp
        #iptables -N forwarding_icmp
        
        ## ipv4 DoS
        #iptables -N DOS_INPUT
        #iptables -N DOS_FORWARD
        
        #iptables -N SYN_FLOODING
	#iptables -N PORT_SCAN
	#iptables -N BAD_PING
	#iptables -t mangle -N DOS_LAND_ATTACK_LOG 

	## parental control
	#iptables -N web_filter
		
	## nat, session limit, port forwarding and port triggering
	#iptables -N forwarding_rule_nat
	#iptables -N forwarding_session_limit
	#iptables -N forwarding_rule_porttrigger
		
	#iptables -t nat -N prerouting_rule_porttrigger
        #iptables -t nat -N prerouting_rule_filter
        #iptables -t nat -N prerouting_rule_nat
        #iptables -t nat -N postrouting_rule

	## ipv6 firewall
        #ip6tables -N input_rule
        #ip6tables -N forwarding_rule

        ### currently we put firewall apply in the hotplug event ###  
	#/lib/firewall/configure_firewall
	#/lib/firewall/configure_firewall6
		
	## iptables app reorder
	#/lib/firewall/iptables_app_order

}

apply() {

	## DOS, IP filter, ICMP ping
	/lib/firewall/configure_firewall
	
	## iptables app reorder
	/lib/firewall/iptables_app_order
}

EXTRA_HELP="    apply   Apply new rules"
EXTRA_COMMANDS="apply"

cmd=$1

case "$cmd" in
boot) boot;;
apply|stop|start|reload|restart|init)
	## firewall
	iptables -F input_rule
	iptables -F output_igmp
	iptables -F forwarding_rule_filter
	iptables -F lan_local_default
    
	iptables -D INPUT -j input_rule
	iptables -D OUTPUT -j output_igmp
	iptables -D FORWARD -j forwarding_rule_filter
	iptables -D INPUT -j lan_local_default
    
	iptables -D INPUT -j ACCEPT
	iptables -D FORWARD -j ACCEPT
     
	iptables -X input_rule
	iptables -X output_igmp
	iptables -X forwarding_rule_filter
	iptables -X lan_local_default
    
	## icmp filter
	iptables -F input_icmp
	iptables -F forwarding_icmp
    
	iptables -D INPUT -p icmp -j input_icmp
	iptables -D FORWARD -p icmp -j forwarding_icmp
    
	iptables -X input_icmp
	iptables -X forwarding_icmp
    
	## ipv4 DoS
	iptables -F DOS_INPUT
	iptables -F DOS_FORWARD
	iptables -F SYN_FLOODING
	iptables -F PORT_SCAN
	iptables -F BAD_PING
	iptables -t mangle -F DOS_LAND_ATTACK_LOG 

	iptables -D INPUT -j DOS_INPUT 2>/dev/null
	iptables -D FORWARD -j DOS_FORWARD 2>/dev/null
	iptables -t mangle -D PREROUTING -j DOS_LAND_ATTACK_LOG 2>/dev/null
    
	iptables -X DOS_INPUT
	iptables -X DOS_FORWARD
	iptables -X SYN_FLOODING
	iptables -X PORT_SCAN
	iptables -X BAD_PING
	iptables -t mangle -X DOS_LAND_ATTACK_LOG
	
	apply;;
esac
