#!/bin/sh

#rm -rf /tmp/Neighbor*
local Al_mac="$1" 
local Ability="$2" 

zy1905="/tmp/zy1905.json"
if [ -f "$zy1905" ]; then

	L2_Al_mac=$(cat /tmp/zy1905.json | grep -n -A2 $Al_mac | grep -A2 "IEEE1905Id")
	if [ "$L2_Al_mac" != "" ]; then
		
		if [ "$Ability" == "reboot" ]; then		
			L2_reboot=$( cat /tmp/zy1905.json | grep -n -A9 $Al_mac | grep -A9 "IEEE1905Id" | grep "EnableReboot" | grep "true")
			if [ "$L2_reboot" == "" ]; then
				echo "0" > /tmp/Neighbor_reboot_ability
			else
				echo "1" > /tmp/Neighbor_reboot_ability
			fi
		elif [ "$Ability" == "wifi" ]; then
			L2_wifi=$( cat /tmp/zy1905.json | grep -n -A9 $Al_mac | grep -A9 "IEEE1905Id" | grep "EnableInterfacePowerControl" | grep "true")
			if [ "$L2_wifi" == "" ]; then
				echo "0" > /tmp/Neighbor_wifi_ability
			else
				echo "1" > /tmp/Neighbor_wifi_ability
			fi
		else			
			intf_num=$(cat /tmp/zy1905.json | grep -n -A2 $Al_mac | grep -A2 "IEEE1905Id" | tr -d "," | sed -n '3p' | awk -F": " '{print $2}')		 
			intf_num2=Interface.$intf_num   #intf_num2=Interface.14

			neighbor=$(cat /tmp/zy1905.json | grep -n $Al_mac | grep "IEEE1905Id" | awk -F":" '{print $1}')
			neighbor_end=$(cat /tmp/zy1905.json | wc -l)
			neighbor_range=`expr $neighbor_end - $neighbor + 1` 
			
			end_line=$(cat /tmp/zy1905.json | tail -n $neighbor_range | grep -n -A4 $intf_num2 | sed -n '4p' | awk -F"-" '{print $1}')
			end_line2=`expr $neighbor + $end_line`

			range=`expr $end_line2 - $neighbor + 1`

			cat /tmp/zy1905.json | head -n $end_line2 | tail -n $range | sed -n '/5G/{n;p;}' > /tmp/Neighbor_wifi_status
			cat /tmp/zy1905.json | head -n $end_line2 | tail -n $range | sed -n '/2.4G/{n;p;}' >> /tmp/Neighbor_wifi_status
			#cat /tmp/zy1905.json | head -n $end_line2 | tail -n $range | grep -n -A3 "InterfaceId" > /tmp/Neighbor_wifi_status
			
			Neighbor_wifi_status=$(cat /tmp/Neighbor_wifi_status | grep 'On')
			if [ "$Neighbor_wifi_status" == "" ]; then
				echo "0" > /tmp/Neighbor_wifi_status
			else
				echo "1" > /tmp/Neighbor_wifi_status
			fi
		fi
		
	else
		echo "error" > /tmp/Neighbor_reboot_ability
		echo "error" > /tmp/Neighbor_wifi_ability
		echo "error" > /tmp/Neighbor_wifi_status		
	fi
else
	echo "error" > /tmp/Neighbor_reboot_ability
	echo "error" > /tmp/Neighbor_wifi_ability
	echo "error" > /tmp/Neighbor_wifi_status		
fi
	
