#!/bin/sh /etc/rc.common

START=99
STOP=99

start() {

	local lan_ip_segment=$(ifconfig br-lan | grep 'inet addr' | awk '{print $2}' | sed 's/^.*addr://g' | cut -d '.' -f 1-2)
	/usr/sbin/p0f -d -s /tmp/p0f.sock -i br-lan -f /etc/appflow/p0f.fp
	/usr/bin/netprobe -i /etc/config/cc -t 10 -c /usr/bin -a /proc/net/arp -d /tmp/dhcp.leases -o /tmp/output -s /tmp/p0f.sock -u $lan_ip_segment -k /tmp/s -p /tmp/associ_info & 
	/sbin/lltd.sh
	
}

stop() {
	killall -9 netprobe
}
