#!/bin/sh
# Copyright (C) 2006 OpenWrt.org

. /etc/functions.sh

local sys_mode=$(get_sys_mode)

[ "$sys_mode" == "2" -o "$sys_mode" == "3" ] && {
	insmod hw_nat
	exit 0
}

##check hw_nat
config_load network                                   
config_get wan_proto wan proto

config_load qos
config_get qos_enable general enable

chk_web_filter=$(cat /etc/config/parental |grep "1" |grep -v "ipaddr"|grep -v "keywords")

if [ "$wan_proto" == "pptp" ] || [ -n "$chk_web_filter" ] || [ "$qos_enable" == "1" ]; then
	rmmod hw_nat
else
	insmod hw_nat
fi
