{
	"For better security, please enter a password that at least 8 characters long, and has at least one number, letter, and symbol in it.":"공유기 보안을 위해 반드시 숫자, 영어, 특수문자가 모두 포함된 8자리 이상의 비밀번호를 입력하시기 바랍니다.",
	"The admin password is used to log in to this configuration interface.<br>It is highly recommended that you create a password to keep your device secure.":"관리자 비밀번호는 본 공유기의 설정화면 접속시 사용됩니다. 임의의 사용자가 설정을 변경하는 문제를 차단하시려면 비밀번호를 설정하여 주십시오.",
	"This page lets you save or restore your device's current settings. You can also reset your device to the factory defaults or reboot the device. Please note that resetting your device will erase all settings and rules you have created.":"설정값을 파일로 백업하고 필요시 공유기 설정을 복구할 수 있습니다. 시스템 초기화는 모든 공유기 설정을 공장 출하시 상태로 복구합니다.",
	"WI-FI PROTECTED SETUP":"WPS 설정",
	"(minutes)":"(분)",
	"(compatibility for some DHCP Clients)":"DHCP 단말과의 호환성 문제가 발생시 사용합니다.",
	"Language packs must be in .lng format; please try again.":"언어팩은 파일 확장자가 lng 형식이어야 합니다. 다시 확인하여 주십시오.",
	"Firmware files must be in .bin format; please try again.":"펌웨어는 파일 확장자가 bin 형식이어야 합니다. 다시 확인하여 주십시오.",
	"\"Create User\" manage access to your storage devices or use the Guest account (guest/guest) to access the Guest Folder. After plugging in an SD card or USB storage drive, the new device will appear in the list with a link to it. You can then use this link to connect the drive and login with a user account.":"본 항목에서 USB 스토리지(SharePort) 를 사용할 수 있는 계정을 생성하고 계정별 권한을 조정할 수 있습니다.",
	"<b>Note</b>: If you are using a PPPoE connection, you will need to remove or disable any PPPoE client software running on your computers. ":"참고 : PPPoE 방식인 경우, 윈도우 상에 별도의 접속 프로그램이나 광대역 연결이 설정되어 있을 수 있습니다. 공유기 설정전에 해당 프로그램을 삭제하여 주십시오.",
	"Please enter a value between 0 and FF":"16진수로 입력하여 주십시오. (0~9/A~F/a~f)",
	"Please enter a value between 0 and FF.":"16진수로 입력하여 주십시오. (0~9/A~F/a~f)",
	"Day hour minute second":"0 일 0 시 0 분 0 초",
	"Step1: Install your device":"1 단계 : 인터넷 방식 자동감지 및 설정",
	"Step 1: Install your device":"1 단계 : 인터넷 방식 자동감지 및 설정",
	"1.Please go to Settings > Wi-fi, and choose":"1. [설정] > [무선(Wi-Fi)] 메뉴로 이동합니다.",
	"Please enter a password that is 10 hex digits long.":"16진수를 이용하여 10자리로 비밀번호를 입력하여 주십시오.",
	"Please enter a password that is 13 ASCII characters long.":"ASCII 문자를 이용하여 13자리로 비밀번호를 입력하여 주십시오.",
	"Please enter a DHCP Lease Time between 1 and 10800.":"DHCP IP 임대 시간을 1~10800 사이의 값으로 입력하여 주십시오.",
	"Step2: Configure your Network and Wi-Fi settings":"2 단계 : 무선(Wi-Fi) 설정",
	"Step 2: Configure your Network and Wi-Fi settings":"2 단계 : 무선(Wi-Fi) 설정",
	"2.4GHz Wi-Fi Network Name":"2.4GHz의 Wi-Fi 네트워크 이름",
	"Guest Zone 2.4GHz":"2.4GHz 멀티SSID",
	"2.4GHz Wi-Fi Password":"2.4GHz의 Wi-Fi 비밀번호",
	"2.4GHz Guest Zone":"2.4GHz 멀티SSID",
	"2.4GHz Wi-Fi Name (SSID)":"2.4GHz 무선 이름(SSID)",
	"20 MHz":"20 MHz",
	"Auto 20/40 MHz":"자동 20/40 MHz",
	"Auto 20/40/80 MHz":"자동 20/40/80 MHz",
	"Please enter a password that is 26 hex digits long.":"16진수를 이용하여 26자리로 비밀번호를 입력하여 주십시오.",
	"Step3: Set your router password":"3 단계 : 관리자 비밀번호 설정",
	"Step 3: Set your router password":"3 단계 : 관리자 비밀번호 설정",
	"A 3G/4G broadband profile was not retrieved or the dial-up attempt failed.":"3G/4G 연결 프로파일을 수신하지 못하였거나 전화 연결을 하지 못하였습니다.",
	"3G/4G Network":"3G/4G 방식",
	"3G/4G Network ":"3G/4G 방식",
	"3G/4G Data":"3G/4G 데이터",
	"3G/4G Wireless USB":"3G/4G USB 방식",
	"Step4: Set mydlink service":"4 단계 : Mydlink 서비스 등록",
	"Step 4: Set up mydlink service":"4 단계 : Mydlink 서비스 등록",
	"Please enter a password that is 5 ASCII characters long.":"ASCII 문자를 이용하여 5자리로 비밀번호를 입력하여 주십시오.",
	"Guest Zone 5GHz":"5GHz 멀티 SSID",
	"5GHz Guest Zone":"5GHz 멀티SSID",
	"5GHz Wi-Fi Name (SSID)":"5GHz 무선 이름",
	"5GHz Wi-Fi Network Name":"5GHz 무선(Wi-Fi) 이름",
	"5GHz Wi-Fi Password":"5GHz 무선 비밀번호",
	"Copy to 5GHz":"5GHz 도 동일하게 설정",
	"6rd":"6rd",
	"6rd DHCPv4 Option":"6rd DHCPv4",
	"6rd IPv6 Prefix":"6rd IPv6 Prefix",
	"6rd Configuration":"6rd 설정",
	"6rd Border Relay IPv4 Address":"6rd IPv4 주소 릴레이",
	"6RD MANUAL CONFIGURATION":"6rd 수동 설정",
	"6to4 Relay":"6to4 릴레이",
	"6to4":"6to4",
	"6to4 Address":"6to4 주소",
	"Between 8 and 63 characters":"8 - 63 자",
	"802.11 Mode":"802.11 모드",
	"802.11a only":"802.11a 전용",
	"Mixed 802.11a/n":"802.11a+n",
	"Mixed 802.11a/n/ac":"802.11a+n+ac",
	"802.11ac only":"802.11ac 전용",
	"Mixed 802.11ac/a/n":"802.11ac+a+n",
	"Mixed 802.11ac/n":"802.11ac+n",
	"802.11b only":"802.11b 전용",
	"Mixed 802.11b/g":"802.11b/g 혼용",
	"Mixed 802.11b/g/n":"802.11b/g/n 혼용",
	"802.11g only":"802.11g 전용",
	"Mixed 802.11g/b":"802.11b+g",
	"Mixed 802.11g/n":"802.11g/n 혼합",
	"802.11n only":"802.11n 전용",
	"Mixed 802.11n/ac":"802.11ac+n",
	"Mixed 802.11n/g":"802.11n+g",
	"AFTR IPv6 Address":"AFTR IPv6 주소",
	"AirPlay Status":"AirPlay 상태",
	"Enable Anti-spoof Checking":"Anti-spoof 검사 사용함",
	"APN":"APN",
	"B4 IPv4 Address":"B4 IPv4 주소",
	"bytes":"bytes",
	"CHAP":"CHAP",
	"Destination IP Address Range":"목적지 IP 주소 범위",
	"DestNetwork":"목적지 네트워크",
	"DHCP IP Address Range":"DHCP IP 주소 범위",
	"Please enter valid IP values (0-254) for the DHCP IP address range.":"DHCP IP 주소 범위를 0~254 사이의 값으로 입력하여 주십시오.",
	"DHCP Renew":"DHCP 새로고침",
	"DHCP Network":"유동 IP 방식",
	"DHCP Release":"DHCP 연결끊기",
	"DHCP Server":"DHCP 서버",
	"DHCP Connection (Dynamic IP Address)":"유동 IP 방식",
	"DHCP Lease Time":"DHCP 유효 시간",
	"The DHCP Lease Time field cannot be blank.":"DHCP 임대 시간을 입력하여 주십시오.",
	"DHCP Lease Time must between 1~10800.":"DHCP 임대 시간은 1 ~ 10800 사이의 값으로 입력하셔야 합니다.",
	"DHCP Client":"DHCP 클라이언트",
	"DHCP Client ":"DHCP 클라이언트",
	"DHCP-PD":"DHCP-PD",
	"Enable DHCP-PD":"DHCP-PD 사용함",
	"IPv6 Network Assigned by DHCP-PD":"DHCP-PD IPv6",
	"D-Link NTP Server":"D-Link NTP 서버",
	"DLNA (Digital Living Network Alliance) is the standard for the interoperability of Network Media Devices (NMDs).":"DLNA 는 별도의 설정을 하지 않더라도 DLNA가 지원되는 장비간 자동으로 동기화하는 표준 규격입니다.",
	"DLNA (Digital Living Network Alliance) is the standard for the interoperability of Network Media Devices (NMDs). The user can enjoy multi-media applications (music, pictures and videos) on your network connected PC or media devices. Web File Access allows you to use a web browser to remotely access files stored on an SD card or USB storage drive plugged into the router.":"DLNA가 지원되는 스마트 TV 및 비디오 게임기에서 USB 스토리지와 자동으로 동기화됩니다.",
	"SharePort allows you to share photos, music, movies and files simply by connecting a USB drive to your router. Access your files locally and remotely using the free mydlink SharePort app for your iOS or Android devices, or access them on a computer through the SharePort Web Access. The built-in Digital Living Network Alliance (DLNA) media server allows you to stream multimedia content to any DLNA compliant devices such as smart TVs and games consoles.":"쉐어포트(SharePort)는 공유기에 장착한 USB 저장장치에 보관된 사진, 음악, 동영상, 파일을 공유하는 기능입니다. 스마트폰등에서는 mydlink SharePort 앱을 이용하여 로컬 및 원격으로 접속하실 수 있으며, PC 에서는 웹브라우저를 이용하여 쉽게 접속하실 수 있습니다. DLNA 미디어 서버는 DLNA 를 지원하는 스마트TV 및 게임콘솔에서 멀티미디어 파일을 실시간으로 재생할 수 있도록 하는 기능입니다.",
	"DLNA technology allows you to enjoy your media anywhere, anytime in your home with DLNA-certified devices. Your music can be streamed wirelessly from DLNA-certified DMS (Digital Media Server) devices. You can also stream music to the speaker connects to your device through iOS device at home effortlessly.":"DLNA 기술은 DLNA 인증 장치 와 함께 언제 어디서나 가정에서 미디어를 즐길 수 있습니다. 음악은 DLNA 인증 DMS ( 디지털 미디어 서버) 장치에서 무선으로 스트리밍 할 수 있습니다. 또한 쉽게 ​​집에서 iOS 장치를 통해 장치에 연결 된 스피커로 음악을 스트리밍 할 수 있습니다.",
	"DLNA Renderer":"DLNA Renderer",
	"DLNA Renderer Status":"DLNA 상태",
	"DLNA Media Server":"DLNA 서버",
	"DLNA Media Server Configuration":"DLNA 서버 설정",
	"DLNA Media Server Name":"DLNA 서버 이름",
	"Enable DMZ Host":"DMZ 호스트 사용함",
	"Enable DMZ":"DMZ 호스트 사용",
	"DNS":"DNS",
	"Enable DNS Relay":"DNS 릴레이 사용",
	"DNS Server":"DNS 서버",
	"The dns server cannot be equal to the IP address.":"DNS 주소를 IP 주소와 다른 값으로 입력하여 주십시오.",
	"Please enter a dns server.":"DNS 서버 주소를 입력하여 주십시오.",
	"DNS Type":"DNS 방식",
	"DS-Lite":"DS-라이트",
	"DS-Lite DHCPv6 Option":"DS-Lite DHCPv6",
	"DS-Lite Configuration":"DS-Lite 설정",
	"Dynamic IP (DHCP)":"유동 IP 방식 (DHCP)",
	"DHCPPPPoE": "Dynamic IP (PPPoE)",
	"Dynamic IP (L2TP)":"유동 IP (L2TP)",
	"Dynamic IP (PPTP)":"유동 IP (PPTP)",
	"E-mail Address (Account Name)":"이메일 주소",
	"GatewayWithWiFi":"무선 게이트웨이",
	"HT20/40 Coexistence":"HT20/40 자동 전환",
	"http":"HTTP",
	"Enable HTTPS Server":"HTTPS 서버 활성화",
	"Use HTTPS":"HTTPS 사용",
	"Ignore":"무시",
	"IP":"IP",
	"IP / Domain name":"IP / 도메인 이름",
	"IP Address":"IP 주소",
	"Please enter an IP address range.":"IP 주소 범위를 입력하여 주십시오.",
	"DMZ IP Address":"DMZ IP 주소",
	"Please enter or select an IP address.":"IP 주소를 입력하거나 선택하여 주십시오.",
	"Please enter an IP address.":"IP 주소를 입력하여 주십시오.",
	"The IP pool range is invalid.":"IP 주소 할당 범위가 올바르지 않습니다.",
	"IPSec (VPN)":"IPSec (VPN) 지원",
	"IPv4":"IPv4",
	"IPv4 Network":"IPv4 네트워크",
	"IPv4 Connection Type must to be PPPoE Session":"IPv4 연결 방식이 PPPoE 로 설정되어야 합니다.",
	"WAN IPv4 Address":"IPv4 인터넷 주소",
	"Turn IPv4 Filtering OFF":"IPv4 규칙 사용안함",
	"Turn IPv4 Filtering ON and ALLOW rules listed":"등록한 IPv4 규칙만 허용",
	"Turn IPv4 Filtering ON and DENY rules listed":"등록한 IPv4 규칙만 차단",
	"Ipv4":"IPv4",
	"IPv4 Rules":"IPv4 규칙",
	"The IPv4 rule section is an advance feature used to deny or allow traffic from passing through the device.":"IPv4 연결에 대한 특정 네트워크 트래픽을 허용 또는 차단하는 기능입니다.",
	"IPv4 Multicast Streams":"IPv4 멀티캐스트 지원",
	"IPv4 Device Management Interface":"IPv4 관리 인터페이스",
	"IPv6 in IPv4 Tunnel":"IPv6 - IPv4 터널",
	"Share with IPv4":"IPv4 공유",
	"IPv6":"IPv6",
	"IPv6 Address":"IPv6 인터넷 주소",
	"IPv6 PPPoE is share with IPv4 PPPoE. Please change IPv6 WAN protocol to PPPoE at first.":"IPv6 PPPoE 방식은 IPv4 PPPoE 방식과 연동되어 있습니다. 먼저 IPv6 연결 방식을 변경하여 주십시오.",
	"Assign IPv6 Prefix":"IPv6 Prefix 할당",
	"IPv6 Default Gateway":"IPv6 기본 게이트웨이",
	"IPv6 Network":"IPv6 네트워크",
	"Please choose one IPv6 connection type besides Link-Local Only, 6to4, 6rd, and IPv6 in IPv4 Tunnel !":"IPv6 연결 방식에는 Link-Local, 6to4, 6rd, IPv6-IPv4 터널이 있습니다. 사용하고 있는 IPv6 서비스를 확인하여 선택하여 주십시오.",
	"Router IPv6 Address":"공유기 IPv6 주소",
	"IPv6 Address Range (End)":"IPv6 주소 범위(끝)",
	"IPv6 Address Range (Start)":"IPv6 주소 범위(시작)",
	"IPv6 Address Lifetime":"IPv6 주소 유효 시간",
	"Please enter an IPv6 address.":"IPv6 주소를 입력하여 주십시오.",
	"Turn IPv6 Filtering OFF":"IPv6 규칙 사용안함",
	"Turn IPv6 Filtering ON and ALLOW rules listed":"등록한 IPv6 규칙만 허용",
	"Turn IPv6 Filtering ON and DENY rules listed":"등록한 IPv6 규칙만 차단",
	"Ipv6":"IPv6",
	"IPv6 ULA SETTINGS":"IPv6 ULA 설정",
	"Please enter a IPv6 dns server.":"IPv6 DNS 서버 주소를 입력하여 주십시오.",
	"IPv6 DNS SETTINGS":"IPv6 DNS 설정",
	"IPv6 WAN Default Gateway":"IPv6 기본 게이트웨이",
	"IPv6 Simple Security":"IPv6 간단한 보안",
	"Please enter a IPv6 gateway address.":"IPv6 게이트웨이 주소를 입력하여 주십시오.",
	"IPv6 Rules":"IPv6 규칙",
	"The IPv6 rule section is an advance feature used to deny or allow traffic from passing through the device.":"IPv6 연결에 대한 특정 네트워크 트래픽을 허용 또는 차단하는 기능입니다.",
	"Your router's built-in firewall also supports IPv6. Some applications or clients may require special adjustment for better performance or extra protection.":"IPv6 연결에 대한 특정 네트워크 트래픽을 허용 또는 차단하는 기능입니다.",
	"IPv6 Multicast Streams":"IPv6 멀티캐스트 지원",
	"IPv6 Connection Type":"IPv6 연결 방식",
	"IPv6 Device Management Interface":"IPv6 장치 관리 인터페이스",
	"ISP":"ISP",
	"ISP ":"ISP",
	"Kbits/sec":"Kbits/sec",
	"KByte/sec":"Kbits/sec",
	"L2TP IP Address":"L2TP IP 주소",
	"L2TP Gateway IP Address":"L2TP 게이트웨이 IP 주소",
	"L2TP Server":"L2TP 서버",
	"L2TP Server IP Address":"L2TP 서버 IP 주소",
	"L2TP Subnet Mask":"L2TP 서브넷 마스크",
	"LAN":"LAN",
	"LAN IP Address":"LAN IP 주소",
	"The LAN IP address cannot be the same as the WAN IP address.":"로컬 IP 주소가 인터넷 IP 주소와 달라야 합니다.",
	"LAN IPv6 ULA":"LAN IPv6 ULA",
	"LAN IPv6 Link-Local Address":"로컬 IPv6 Link-Local 주소",
	"The LAN IPv6 Link-Local Address is the IPv6 Address that you use to access the Web-based management interface.":"LAN IPv6 Link-Local 주소는 본 장치의 설정화면에 접속할 수 있는 IPv6 주소입니다.",
	"LAN IPv6 Address":"로컬 IPv6 주소",
	"LAN subnet conflicts with WAN subnet.":"로컬 서브넷 값과 인터넷 서브넷 값이 충돌됩니다. 다시 확인하여 주십시오.",
	"LAN IPv6 ADDRESS SETTINGS":"로컬 IPv6 주소 설정",
	"Send When Log Full":"Log-Full 전송",
	"MAC Address":"MAC 주소",
	"Mac Address Clone":"MAC 주소 복사",
	"MAC Address Clone":"MAC 주소 복사",
	"MTU":"MTU",

	"mydlink":"mydlink",
	"mydlink Registration":"mydlink 등록",
	"mydlink Regristration":"mydlink 등록",
	"mydlink Account":"mydlink 계정",
	"mydlink Service":"mydlink 서비스",
	"I accept the mydlink":"mydlink 계정 설정을 허용합니다.",
	"Could not connect to mydlink; please check your Internet connection.":"Mydlink 서비스에 연결할 수 없습니다. 인터넷 연결을 먼저 확인하여 주십시오.",
	"Update Time Using an NTP Serevr":"NTP 서버 동기화 사용함",
	"Update Time Using an NTP Server":"NTP 서버 동기화 사용함",
	"NTP Server":"NTP 서버",
	"OK":"완료",
	"PAP":"PAP",
	"PBC":"PBC",
	"PBC Start":"PBC 연결 시작",
	"PIN":"PIN",
	"PIN Code":"PIN 코드",
	"Device PIN":"PIN 코드",
	"Generate New PIN":"새로운 PIN 코드 생성",
	"PIN Start":"PIN 코드 연결 시작",
	"Save Device PIN":"PIN 코드 저장",
	"Port Range":"포트 범위",
	"PPPoE":"PPPoE",
	"The PPPoE user name or password is incorrect.":"PPPoE 사용자 이름 또는 비밀번호가 올바르지 않습니다.",
	"PPPoE Session":"PPPoE 방식",
	"PPTP":"PPTP",
	"PPTP Gateway IP Address":"PPTP 게이트웨이 주소",
	"PPTP Server":"PPTP 서버",
	"PPTP Server IP Address":"PPTP 서버 IP 주소",
	"PPTP Subnet Mask":"PPTP 서브넷 마스크",
	"PPTP IP Address":"PPTP IP 주소",
	"PrefixLen":"Prefix 길이",
	"QoS Engine":"QoS 설정",
	"root":"root(루트)",
	"RTSP":"RTSP",
	"SD Card":"SD 카드",
	"The SD card has an unsupported file system format.":"SD 카드가 지원되지 않는 파일형식으로 포맷되어 있습니다.",
	"SharePort":"SharePort",
	"To access your storage with SharePort Web Access, click here.":"USB 스토리지에 접속하시려면, 본 항목을 클릭하여 주십시오.",
	"SharePort Web Access":"SharePort 웹 접속",
	"To access your storage with SharePort Web Access,":"USB 스토리지에 접속하시려면,",
	"To access your storage with SharePort Web Access, ":"USB 스토리지에 접속하시려면,",
	"SIM Card Status":"SIM 카드 상태",
	"SIM Card Status ":"SIM 카드 상태",
	"SIP":"SIP",
	"SLAAC+Stateless DHCP":"SLAAC + Stateless DHCP",
	"SMTP Server Address":"SMTP 서버 주소",
	"Please enter an SMTP server address.":"SMTP 서버 주소를 입력하여 주십시오.",
	"SMTP Server Port":"SMTP 서버 포트",
	"Source IP Address Range":"출발지 IP 주소 범위",
	"Enable SPI IPv4":"SPI IPv4 사용함",
	"SSID":"SSID",
	"Static IP (L2TP)":"L2TP 고정 IP 방식",
	"Static IP (PPPoE)":"Static IP (PPPoE)",
	"Static IP (PPTP)":"Static IP (PPTP)",
	"Static IP (Static)":"고정 IP 방식",
	"Enable Logging to Syslog Server":"Syslog 서버 사용함",
	"SysLog Server IP Address":"Syslog 서버 IP 주소",
	"TCP Port":"TCP 포트",
	"This page allows you to define custom routes to define how data traffic is moved around your network":"목적지 IP 주소로 네트워크 데이터가 전달되는 경로를 고정으로 지정할 수 있습니다.",
	"This page lets you enable and configure a Wi-Fi Guest Zone. Users connected to a Guest Zone cannot communicate or detect devices on your home network unless Internet Access Only is disabled under Home Network Access.":"목적지 IP 주소로 네트워크 트래픽이 전달되는 경로를 고정으로 지정할 수 있습니다.",
	"UDP Port":"UDP 포트",
	"Enable ULA":"ULA 사용",
	"ULA Prefix":"ULA Prefix",
	"UPnP":"UPnP",
	"UPnP Media Server":"UPnP 미디어 서버",
	"UPnP Media Server:":"UPnP 미디어 서버 : ",
	"USB":"USB",
	"The USB drive has an unsupported file system format.":"USB 저장장치가 지원되지 않는 파일형식으로 포맷되어 있습니다.",
	"USB Name":"USB 이름",
	"USB Device":"USB 장치",
	"USB Device Name":"USB 장치 이름",
	"USB Storage":"USB 저장 장치",
	"USB Port":"USB 포트",
	"VIRTUAL":"가상",
	"WAN IP Address":"WAN IP 주소",
	"WAN IPv6 Address":"IPv6 인터넷 주소",
	"WAN Port Speed":"인터넷(WAN) 포트 속도",
	"WEP":"WEP",
	"WEP password length is 10 or 26, password type must be Hexadecimal.":"WEP 비밀번호는 16진수를 이용하여 10 또는 26자리로 입력하실 수 있습니다.",
	"SELECT WI-FI NETWORK":"무선(Wi-Fi) 선택",
	"WI-FI CONNECTION SETUP WIZARD":"무선 설정 마법사",
	"Wi-Fi":"Wi-Fi",
	"Wi-Fi 5GHz":"5GHz 무선(Wi-Fi)",
	"Wi-Fi 5GHZ":"Wi-Fi 5GHz",
	"Wi-Fi Password":"무선(Wi-Fi) 비밀번호",
	"Wi-Fi Name (SSID)":"Wi-Fi 이름 (SSID)",
	"Wi-Fi Channel":"Wi-Fi 채널",
	"Wi-Fi Clients":"Wi-Fi 클라이언트",
	"Wi-Fi Client":"Wi-Fi 클라이언트",
	"Wi-Fi Clients (Guest Zone)":"무선 단말(멀티 SSID)",
	"Wi-Fi Clients(Guest Zone)":"무선 단말(멀티 SSID)",
	"Wi-Fi networks":"Wi-Fi 네트워크",
	"Wi-Fi Network:":"Wi-Fi 네트워크 :",
	"from the list of Wi-Fi network services.":"Wi-Fi 목록에서 연결하고자 하는 이름을 선택합니다.",
	"Wi-Fi Network Name":"Wi-Fi 네트워크 이름",
	"Wi-Fi Network Name (SSID)":"Wi-Fi 네트워크 이름 (SSID)",
	"The Wi-Fi Network Name is up to 32 characters. You will need to join your Wi-Fi network using this Network Name (SSID).":"Wi-Fi 네트워크 이름은 최대 32자까지 입력하실 수 있습니다. 무선 연결 시 설정한 Wi-Fi 네트워크 이름으로 연결하여 주십시오.",
	"To setup a Wi-Fi Network you will need to give your Wi-Fi Nerwork a Name(SSID) and Password.":"사용 할 Wi-Fi 네트워크 이름과 접속 비밀번호를 입력하여 주십시오.",
	"To setup a Wi-Fi Network you will need to give your Wi-Fi Network a Name(SSID) and Password.":"사용 할 Wi-Fi 네트워크 이름과 접속 비밀번호를 입력하여 주십시오.",
	"The Wi-Fi connection is not secure.":"선택하신 Wi-Fi 신호는 보안이 설정되어 있지 않습니다.",
	"ENTER WIFI PASSWORD":"무선 비밀번호 입력",
	"Wi-Fi 2.4GHz":"2.4GHz 무선(Wi-Fi)",
	"Wi-Fi Settings":"무선(Wi-Fi) 설정",
	"Wi-Fi Hotspot Client":"Wi-Fi Hot-Spot 방식",
	"WPA password length is 64, password type must be Hexadecimal.":"WPA 비밀번호는 16진수를 이용하여 64 자리로 입력하실 수 있습니다.",
	"WPA/WPA2-Personal":"WPA/WPA2-Personal",
	"WPA-Personal":"WPA-Personal",
	"WPS status":"WPS 상태",
	"xDSL BroadBand (PPPoE)":"XDSL 광대역 (PPPoE)",
	"xDSL Broadband (PPPoE)":"XDSL 광대역 (PPPoE)",
	"xDSL Broadband(PPPoE)":"XDSL 광대역 (PPPoE)",
	"VIRTUAL PUSH BUTTON":"WPS 버튼",
	"Virtual Server":"가상 서버",
	"The Virtual Server option allows you to define a single public port on your router for redirection to an internal LAN IP Address and Private LAN port if required. This feature is useful for hosting online services such as FTP or Web Servers.":"가상 서버는 공유기에서 포트를 열고 사용자의 네트워크에 구성 된 특정 장치에서 사용하는 단일 포트로 트래픽을 통과 시켜주는데 사용됩니다. 이 기능은 FTP나 웹 서버와 같은 온라인 서비스를 호스팅하는데 유용합니다.",
	"Your router helps share a single IP address assigned by your Internet service provider among several clients in your home. Virtual servers are preset port mappings for popular services, like a web or e-mail server, that route traffic to a specified client inside.":"가상 서버는 포트 포워딩처럼 외부에서 내부 서버로 접속을 위한 설정입니다. 포트 포워딩은 외부 접속 포트와 내부 접속 포트가 동일한 경우에 사용하며, 가상서버는 외부 접속 포트와 내부 접속 포트가 다른 경우에 사용합니다.",
	"Visibility Status":"무선 신호 이름 표시",
	"Sign Up":"가입하기",
	"Before Sign up mydlink, the Admin Password of DIR-508L can not be blank.":"Mydlink 서비스에 등록하기 전에, DIR-508L 의 관리자 비밀번호를 설정하여 주십시오.",
	"Highest":"가장 높음",
	"Please enter a value.":"올바른 값을 입력하여 주십시오.",
	"Please enter the Personal Identification Number(PIN) code.":"PIN 코드를 입력하여 주십시오.",
	"Renew":"갱신",
	"Renew IP Address":"IP 주소 연결 갱신",
	"Blocked":"거부",
	"Skip":"건너뛰기",
	"Checking":"확인 중입니다.",
	"Search Songs...":"음악 검색",
	"Search Movie...":"영화 검색...",
	"Scanning...":"검색 중...",
	"No USB device detected":"USB 장치 없음",
	"Guest Zone Wi-Fi Name (SSID)":"게스트 존 Wi-Fi 이름 (SSID)",
	"Gateway":"게이트웨이",
	"Gateway Address":"게이트웨이 주소",
	"Please enter a gateway address.":"게이트웨이 주소를 입력 해주십시오.",
	"Create New Route":"경로 새로 만들기",
	"Edit Route":"경로 수정",
	"Add Route":"경로 추가",
	"Continue":"계속",
	"Always Enable":"계속 사용함",
	"You must accept the terms and conditions to continue.":"계속 진행하시려면, 본 사용권 및 조건에 동의하여 주십시오.",
	"Account Name":"계정 이름",
	"Guest Zone":"멀티 SSID",
	"ALLOW clients access to ONLY these sites":"설정 된 사이트에 접속 허용",
	"Advanced":"고급",
	"Advanced Network":"고급 네트워크",
	"Advanced Network settings allow you to configure some of the more advanced features of your router. It is recommended that you only change these settings if you are  familiar with them, or if you are specifically instructed to do so.":"네트워크 접속/통신을 위한 고급항목의 설정을 변경하실 수 있습니다. 본 설정값은 네트워크 성능에 직접적인 영향을 주게 되오니, 각 항목의 내용을 충분히 숙지하신 후 설정하여 주십시오.",
	"Advanced Settings":"고급 설정",
	"Advanced Settings...":"고급 설정 ...",
	"Static IP":"고정 IP",
	"Static IP Address Connection":"고정 IP 주소 연결",
	"Static IPv6":"고정 IPv6",
	"Static Route":"고정 경로",
	"Static Routes":"고정 경로",
	"Vendor":"공급 업체",
	"Vender":"공급 업체",
	"Require router's admin password":"공유기 관리자 비밀번호를 설정해야 합니다",
	"Router Not Found":"공유기를 감지할 수 없습니다.",
	"Restore Factory Defaults":"시스템 초기화",
	"Reset To Factory Defaults":"시스템 초기화",
	"Restore To Factory Default Settings":"초기 설정으로 복구",
	"Reset To Factory Default Settings":"초기화에 성공했습니다!",
	"Restore to factory default success!":"초기화에 성공했습니다!",
	"Restore Factory Default":"초기화에 성공했습니다!",
	"Management":"관리",
	"Administration":"관리",
	"Management Link":"관리 링크",
	"Admin":"관리자",
	"Admin Password":"관리자 암호",
	"The admin password is used to log in to this configuration interface. It is highly recommended that you create a password to keep your router secure.":"관리자 비밀번호는 본 공유기의 설정화면 접속시 사용됩니다. 임의의 사용자가 설정을 변경하는 문제를 차단하시려면 비밀번호를 설정하여 주십시오.",
	"Please set your Admin Password at least six characters.":"관리자 비밀번호를 최소 6자리로 입력하여 주십시오.",
	"The admin password is used to log in to this configuration interface.":"관리자 비밀번호는 본 공유기의 설정화면 접속시 사용됩니다.",
	"SELECT CONFIGURATION METHOD":"설정 방법",
	"Restore configuration file failed!":"구성 파일을 복원하지 못했습니다!",
	"Restore configuration file success!":"구성 파일의 복원을 성공했습니다!",
	"Save Configuration":"구성 저장",
	"Save Configuration To File":"설정 백업",
	"Routing Between Zones":"게스트 존 라우팅 설정",
	"Home Network Access":"무선 영역간 통신 허용",
	"Country":"국가",
	"Country ":"국가",
	"Please enter a name for your DLNA Media Server.":"DLNA 미디어 서버 이름을 입력하여 주십시오.",
	"All of your IPv6 Internet and network connection details are displayed on this page.":"IPv6 인터넷 및 네트워크 연결 상태를 표시합니다.",
	"Your password must be 13 or 26 characters length.":"무선 비밀번호를 13자리 또는 26자리로 입력하여 주십시오.",
	"Your password must be 5 or 10 characters length.":"무선 비밀번호를 5자리 또는 10자리로 입력하여 주십시오.",
	"Your password must be between 6-15 characters length.":"비밀번호를 6 ~ 15자 범위에서 입력하여 주십시오.",
	"Your password must be at least 8 characters long.":"비밀번호를 최소 8자리로 입력하여 주십시오.",
	"Your password must be between 8-63 characters length.":"무선 비밀번호를 8 ~ 63 자 범위에서 입력하여 주십시오.",
	"Use this section to configure the internal network settings of your Extender. Device Name allows you to configure this device more easily when your network using TCP/IP protocol. You can enter the device name of the Extender into your web browser to access the instead of IP address for configuration. Recommend to change the device name if there're more than one D-Link devices within the subnet.":"공유기의 내부 네트워크 설정을 관리합니다. 공유기에 할당된 IP 주소 대신 장치명을 이용하여 공유기 설정에 접속하실 수 있습니다. 장치명은 관리하기 쉽도록 변경하실 수 있습니다.",
	"Create New Rule":"새 규칙 생성",
	"Edit Rule":"규칙 수정",
	"Add Rules":"규칙 추가",
	"Add Rule":"규칙 추가",

	"It is highly recommended that you create a password to keep your router secure.":"임의의 사용자가 설정을 변경하는 문제를 차단하시려면 비밀번호를 설정하여 주십시오.",
	"Enable Graphical Authentication (CAPTCHA)":"CAPTCHA 인증 사용함",
	"Friday":"금요일",
	"Create New Record":"IPv6 DDNS 설정",
	"Edit Record":"설정 수정",
	"Add Record":"설정 추가",
	"Primary DNS Server":"기본 DNS 서버",
	"Please enter a primary dns server":"기본 DNS 서버 주소를 입력하여 주십시오.",
	"Primary DNS Address":"기본 DNS 주소",
	"Primary IPv6 DNS Server":"기본 IPv6의 DNS 서버",
	"Use Default ULA Prefix":"ULA Prefix 기본값 사용함",
	"Default Gateway":"기본 게이트웨이",
	"The default gateway should be in the same network.":"기본 게이트웨이 주소가 동일 네트워크 대역으로 설정되어야 합니다.",
	"By default, your new D-Link device does not have a password configured for administrator access to the Web-based configuration utility. To secure your new device, please create a password below.":"공유기 보안을 위하여 로그인 비밀번호를 설정하여 주십시오. 비밀번호는 8자 이상의 숫자, 영어, 특수문자를 포함하여 입력하여 주십시오.",
	"Do you have an existing mydlink account":"Mydlink 서비스에 등록하신 계정이 있습니까",
	"Do you have an existing mydlink account?":"Mydlink 서비스에 등록하신 계정이 있습니까",
	"Others":"기타",
	"Finish":"완료",
	"I accept the mydlink terms and conditions.":"Mydlink 사용권 및 조항에 동의합니다.",
	"Date":"날짜",
	"Remaining":"설정 가능 규칙 수",
	"Low":"낮음",
	"My IPv6 Connection is":"IPv6 연결",
	"My LAN Connection is":"LAN 연결은",
	"My Access Device Hard Drive":"접속 드라이브",
	"My Internet Connection is":"인터넷 연결 방식",
	"Internal Port":"내부 포트",
	"The built-in UPnP media server streams music, videos, and photos stored on an attached USB drive to PCs, smartphones, tablets, smart TVs, or other media devices on your network. Web File Access allows you to access files on an attached USB drive through a web browser.":"UPnP 미디어 서버 기능을 통해 USB 스토리지에 저장된 음악, 동영상, 사진을 PC, 스마트TV, 스마트폰 등에서 실시간으로 재생할 수 있습니다.",
	"Yes, I have a mydlink account":"네. Mydlink 서비스 계정을 가지고 있습니다.",
	"Yes, I have a mydlink account.":"네. Mydlink 서비스 계정을 가지고 있습니다.",
	"Network":"네트워크",
	"Network(LAN)":"네트워크 (LAN)",
	"Network (LAN)":"네트워크 (LAN)",
	"Secure your network":"네트워크 보안",
	"Network Status":"네트워크 상태",
	"Network Settings":"네트워크 설정",
	"Network Name(SSID)":"네트워크 이름 ( SSID)",
	"The network id is the same with LAN.":"네트워크 ID 는 동일 로컬 네트워크로 구성되어 있어야 합니다.",
	"Choose a Network...":"네트워크를 선택 ...",
	"Please enter a netmask.":"서브넷 마스크 값을 입력하여 주십시오.",
	"Year/ Month/ Day":"년 / 월 / 일",
	"(Year/ Month/ Day)":"년 / 월 / 일",
	"High":"높음",
	"Visible":"검색허용",
	"Invisible":"숨김",
	"Connect to another uplink router":"다른 무선 공유기로 연결",
	"Downloading":"다운로드 중입니다",
	"Downloading...":"다운로드 중입니다",
	"Next":"다음",
	"Use the following DNS address":"다음 DNS 주소 사용",
	"Use the following IPv6 DNS Servers.":"다음 IPv6 DNS 서버 주소 사용",
	"Diagram":"메뉴",

	"Station":"단말",
	"Are you sure you want to reset the device to its factory default settings?,":"시스템을 초기화 하시겠습니까?",
	"Are you sure you want to reset the device to its factory default settings? This will cause current settings to be lost.":"시스템을 초기화 하시겠습니까? 모든 설정값이 공장 출하 상태로 복구됩니다.",
	"Are you sure you want to restore configuration file?":"설정을 복구하시겠습니까?",
	"You can access your music, pictures and videos from a PC or media device connected to your network.":"본 공유기에 유무선으로 연결된 PC 및 기타 단말에서 저장장치에 접속하실 수 있습니다.",
	"You can register this device with your existing mydlink account. If you do not have one, you can create one now.":"Mydlink 서비스 등록은 [설정] > [Mydlink] 메뉴에서 별도로 진행하실 수 있습니다. 차후 등록하시려면 [건너뛰기] 버튼을 클릭하여 주십시오.",
	"Are you sure you want to change your Internet connection type?":"인터넷 연결 방식을 변경하시겠습니까?",
	"Are you sure you want to change your Internet connection type? ":"인터넷 연결 방식을 변경하시겠습니까?",
	"Are you sure you want to delete":"선택하신 파일을 삭제하시겠습니까?",
	"If you changed the IP address of the router you will need to change the IP address in your browser before accessing the configuration website again.":"공유기 IP 주소를 변경하신 경우, 설정이 완료된 후 변경하신 IP 주소로 재접속하여 주십시오.",
	"You have successfully registered this device to your mydlink account.":"Mydlink 계정에 본 장치를 등록하였습니다.",
	"You can only specify up to 5 folders for access.":"접속할 수 있는 폴더는 최대 5개까지만 선택하실 수 있습니다.",
	"You can change the default device name with another unique name for audio renderer service. Eg. Living Room.":"Audio Renderer 서비스 구분을 위하여 기본 이름을 고유의 이름으로 변경하실 수 있습니다.",
	"Enter the IPv6 address information that you would like to use to access the Web-based management interface.":"설정 화면에 접속할 IPv6 주소를 입력하여 주십시오.",
	"You should choose another IPv4 Internet Connection mode rather than 'DS-Lite' to access the Internet.":"DS-Lite 방식이 아닌 다른 IPv4 인터넷 연결 방식을 선택하여 주십시오.",
	"If you changed the device name you may need to change the IP address in browse to access the device.":"장치 이름을 변경하신 경우, 변경한 값으로 설정화면에 재접속하여 주십시오.",
	"Are you sure you want to reboot the device?,":"시스템을 재시작 하시겠습니까?",
	"Are you sure you want to reset the device?":"시스템을 재시작 하시겠습니까?",
	"You have failed to connect to the Wi-Fi network within the given timeframe, please click on the button below to do it again.":"무선(Wi-Fi) 연결 시간이 초과되었습니다. 다시 시도하여 주십시오.",
	"Do you want to upgrade Firmware?":"펌웨어 업그레이드를 진행하시겠습니까?",
	"Use this section to configure the wireless settings for your D-Link Extender. Please note that changes made on this section may also need to be duplicated on your Wireless Client.":"무선 설정을 변경하시면 현재 연결된 무선 단말의 접속이 끊어집니다. 설정을 완료하신 후, 변경하신 값으로 재연결하여 주십시오.",
	"Use this section to configure the wireless settings for your D-Link Router. Please note that changes made on this section may also need to be duplicated on your Wireless Client.":"D-Link 공유기의 무선 설정을 변경하려면 이 메뉴를 이용합니다. 설정을 변경한 경우에 무선 클라이언트를 다시 연결해야 합니다.",

	"Use this section to configure the wireless settings for your D-Link Router. Please make sure that any changes made in this section will need to be updated on your wireless device.":"공유기 무선 설정을 변경하실 경우, 현재 연결된 무선 단말의 연결이 끊어집니다. 설정을 완료하신 후, 변경하신 무선(Wi-Fi) 이름과 비밀번호를 이용하여 재접속하여 주십시오.",
	"Checking Your Internet connectivity":"인터넷 연결 방식을 자동으로 감지합니다.",
	"Checking Your Internet Connectivity":"인터넷 연결 방식을 자동으로 감지합니다.",
	"Do you want to continue?":"계속 진행하시겠습니까?",
	"Please press Push Button(Physical or Virtual) on the AP or Router you are connecting to within ":"연결하고자 하는 AP 나 공유기에 있는 WPS 버튼을 눌러주십시오.",
	"Select this option if you want to setup your network manually":"수동으로 네트워크 설정을 진행하시려면, 본 항목을 선택하여 주십시오.",
	"Use this section to configure the Wi-Fi Network you would like your DCH-M225 to connect to. Use Site Survey to scan available Wi-Fi networks and select the Wi-Fi Network you would like your DCH-M225 to connect to. Enter the Password of the Wi-Fi Network you selected and click Save.":"DCH-M255 무선 연결을 설정하실 수 있습니다. 무선 신호를 검색하여 연결할 Wi-Fi 이름을 선택하신 후, 접속 비밀번호를 입력하여 주십시오.",
	"QoS prioritizes your network traffic so you can decide what devices should have priority over other devices. For example, you could set a computer that is downloading files to have lower priority than a laptop that is streaming movies to ensure that you can stream movies smoothly without downloads taking up all of your bandwidth.":"QoS 기능은 설정 할 장치를 다른 장치보다 우선 순위로 설정하여 네트워크 트래픽의 우선 순위를 결정 할 수 있습니다. 예를 들어, 고객님의 기기는 다운로드 대역폭을 모두 차지하지 않고도 원활하게 동영상을 스트리밍 할 수 있도록 다른 기기보다 우선 순위에 설정 할 수 있습니다.",

	"Connected clients can be assigned Internet access priority. Click and drag client cards into open slots.":"연결된 단말에 대한 인터넷 트래픽 전송 우선순위를 설정할 수 있습니다. 등록하시려면 원하는 단말을 클릭하여 드래그(Drag) 합니다.",
	"Apply":"저장",
	"Please enter a destination network IP address.":"목적지 IP 주소를 입력하여 주십시오.",
	"Get Help":"도움말",
	"Click here for help.":"도움말을 확인하시려면 본 항목을 클릭하여 주십시오.",
	"Use the same password for both networks":"동일한 비밀번호를 입력하여 주십시오",
	"Dynamic DNS":"DDNS",
	"Dynamic DNS (DDNS) allows you to use an easy to remember domain name such as www.[YourDomainName].com to reach your router's dynamically assigned IP address. This is useful when hosting a web, FTP, or game server, and allows you to reach your server no matter what your IP address has changed to. D-Link offers a free DDNS service that you can use through www.DLinkDDNS.com.":"DDNS 는 현재 사용중인 공인 IP 주소를 등록한 도메인으로 연결함으로써, 외부에서 내부 서버로 접속시, 도메인으로 접속할 수 있습니다. 본 서비스를 이용하기 위해서는, www.DLinkDDNS.com 에 접속하시어 회원가입을 완료하고 사용할 도메인 이름을 설정하여 주십시오.",


	"Dynamic Domain Name Service allows your router to associate an easy-to-remember domain name such as [YourDomainName].com with the regularly changing IP address assigned by your Internet Service provider. This feature is helpful when running a virtual server.":"DDNS는 공인IP를 도메인 이름으로 변경하여 기억하기 쉽게 사용 할 수 있는 기능입니다. 공유기에 설정 된 공인 IP 주소가 변경 되더라도 문제없이 [YourDomainName].com 처럼 사용하여 웹, FTP, 게임 서버를 호스팅 할 때 유용하게 사용 할 수 있습니다.",
	"Enable Dynamic DNS":"유동 DNS 사용함",
	"Dynamic IP":"유동 IP",
	"Back":"뒤로",
	"Registered":"등록됨",
	"Router":"공유기",
	"Router Advanced Lifetime":"공유기 고급 라이프타임",
	"The router is not connected to the Internet.":"본 공유기가 인터넷에 연결되어 있지 않습니다.",
	"The Router will not be reprogrammed.,":"공유기 설정을 재구성할 수 없습니다.",
	"Router IP Address":"공유기 IP 주소",
	"to":"에",
	"Log In":"로그인",
	"Sign In":"로그인",
	"Login":"로그인",
	"Please switch your browser to normal mode before login.":"로그인하기 전에 일반 모드로 브라우저를 전환하십시오.",
	"local":"로컬",
	"Local IP":"로컬 IP",
	"Local IPv4 Address":"로컬 IPv4 주소",
	"Local IPv6 Address":"로컬 IPv6 주소",
	"Local Domain Name":"로컬 도메인 이름",
	"Local Access":"로컬 액세스",
	"Allow Local Access":"로컬 액세스 허용",
	"Local Connectivity Only":"로컬 연결로만 사용",
	"Save Settings To Local Hard Drive":"설정 백업",
	"Load Settings From Local Hard Drive":"설정 복구",
	"Repeater":"리피터",
	"Use Link-Local Address":"Link-Local 주소 사용",
	"Link-Local Address":"Link-Local 주소 ",
	"Netmask":"서브넷 마스크",
	"End range must be greater than the start range":"끝 IP 주소는 시작 IP 주소보다 커야 합니다.",
	"All Week":"매주",
	"Matrix":"매트릭스",
	"Metric":"매트릭스",
	"Your Wi-Fi network needs to be enabled in order to turn on Guest Zone network. Would you like to turn on both?":"멀티 SSID 를 설정하기 위해서는 기본 무선 기능이 켜져 있어야 합니다. 지금 바로 무선 기능을 켜시겠습니까?",
	"2.Enter the password you just setup when prompted.":"2. 무선(Wi-Fi) 비밀번호를 입력합니다.",
	"Model Name":"모델명",
	"Reconnect Mode":"재연결 방식",
	"Allow all users to access (No password)":"모든 사용자 접속 허용(비밀번호 없음)",
	"All Devices":"모든 단말",
	"Mobile":"모바일",
	"Connect to the Wi-Fi network from your mobile device or PC":"무선(Wi-Fi) 연결",
	"Summary":"목록",
	"Thursday":"목요일",
	"Destination IP":"목적지 IP",
	"Destination Network":"목적지 네트워크",
	"Wireless":"무선",
	"Wireless(Wi-Fi)":"무선 (Wi-Fi)",
	"Wireless Network Name":"무선(Wi-Fi) 이름",
	"Please select a wireless station.":"무선(Wi-Fi) 단말을 선택하여 주십시오.",
	"Wireless Mode":"무선 동작 방식",
	"Please enter Wi-Fi Password to establish wireless connection":"연결할 무선(Wi-Fi) 의 접속 비밀번호를 입력하여 주십시오.",
	"Select this option if your wireless device supports WPS(Wi-Fi Protected Setup)":"WPS 기능을 지원하지 않는 경우, 본 항목을 선택하여 주십시오.",
	"Search Documents...":"문서 검색",
	"Unregistered":"등록안됨",
	"Desktop":"바탕 화면",
	"Firewall":"방화벽 설정",
	"Firewall Setting":"방화벽 설정",
	"Firewall Settings":"방화벽 설정",
	"Battery":"배터리",
	"Web File Access cannot be used when the battery is low. Please charge the battery first.":"배터리가 부족하면 웹 파일 액세스를 사용할 수 없습니다. 먼저 배터리를 충전하십시오.",
	"The firmware cannot be upgraded when the battery is low. Please charge the battery first.":"배터리가 부족하면 펌웨어를 업그레이드 할 수 없습니다. 먼저 배터리를 충전하십시오.",
	"The battery currently has less than 15% charge; please charge the battery before upgrading the firmware.":"현재 베터리의 충전상태가 15% 이하입니다. 펌웨어 업그레이드 전에 배터리를 충전하십시오.",
	"Your changes are being saved, you will soon be disconnected.":"변경 사항을 저장하고 있습니다. 연결이 곧 끊어집니다.",
	"Your changes are being saved. When reconnecting to this device, please use the new Wi-Fi name and password you created.":"변경된 설정을 저장하기 위해 공유기가 재부팅 중 입니다. 공유기에 다시 연결하려면, 새로 만든 Wi-Fi 네트워크 이름과 비밀번호를 사용하십시오.",
	"There is unsaved data on this page. Do you want to abandon it?":"변경된 사항이 적용되지 않습니다. 계속 하시겠습니까?",
	"View":"보기",
	"Security":"보안",
	"Security Check":"보안 체크",
	"Security Mode":"보안 모드",
	"Please note that when using WEP security, WPS will be disabled.":"보안방식을 WEP 로 설정하실 경우, WPS 기능은 사용하실 수 없습니다.",
	"Your password must be 5 or 10 or 13 or 26 length.":"보안키는 5자리, 10자리, 13자리, 26자리로 입력하여야 합니다.",
	"Secondary DNS Server":"보조 DNS 서버",
	"Secondary DNS server should not be the same as Primary DNS server.":"보조 DNS 서버 주소는 기본 DNS 주소와 달라야 합니다.",
	"Secondary DNS Address":"보조 DNS 주소",
	"Secondary IPv6 DNS Server":"보조 IPv6 DNS 서버",
	"Click to repair":"복구",
	"Restore":"복원",
	"Do not close the page or power off the service until the restore configuration file is complete!":"구성 파일의 복원이 완료 될때까지 해당 페이지를 닫거나 전원을 끄지 마세요!",
	"The router would not support the subnet mask which length is less than Class A.":"공유기는 A 클래스 이하의 서브넷 마스크 값을 지원하지 않습니다.",
	"minutes":"분",
	"Disconnect":"연결 해제",
	"Non-Registered":"미등록",
	"Password:(optional)":"비밀번호 : (선택 사항)",
	"Password Length":"암호 길이",
	"Invalid password or captcha, please try again.":"비밀번호 혹은 보안문자가 올바르지 않습니다. 다시 확인하여 주십시오.",
	"Invalid password, please try again.":"비밀번호가 잘못되었습니다 다시 시도하십시오.",
	"Your password must be 13 characters length":"비밀번호를 13 자리로 입력하여 주십시오.",
	"Your password must be between 6-15 characters length":"비밀번호를 6 ~ 15 자리로 입력하여 주십시오.",
	"Your password must be between 8-63 characters length":"비밀번호를 8 ~ 63 자리로 입력하여 주십시오.",
	"Please enter a password.":"비밀번호를 입력하세요.",
	"Disbled":"사용 안 함",
	"Disabled":"사용 안 함",
	"Enabled":"사용 함",
	"Enable Automatic DHCP-PD in LAN":"LAN의 자동 DHCP-PD 사용",
	"Available Space":"사용 가능 공간",
	"Click \"Next\" to find available Wi-Fi hotspot networks.":"사용 가능한 Wi-Fi 핫스팟 네트워크를 찾기 위해 \"다음\"을 클릭합니다.",
	"Available hotspot networks":"사용 할 수 있는 핫스팟 네트워크",
	"Manual":"매뉴얼",
	"License Agreement":"사용권 동의",
	"Users":"사용자",
	"Create User":"사용자 만들기",
	"User List":"사용자 목록",
	"Edit User Settings":"사용자 설정을 편집합니다",
	"User Name":"사용자 이름",
	"Edit User Profile":"사용자 프로필 편집",
	"The admin has read/write access and can change passwords, while the user has read-only access. By default there is no password configured. It is highly recommended that you create a password to keep your router secure.":"사용자 계정으로 엑세스 할 경우 설정 내용을 보기만 할 수 있고, 관리자 계정은 보기 및 변경이 가능합니다. 기본적으로 구성 된 암호는 없습니다. 이것은 공유기의 보안을 유지하기 위해서 위험한 내용이므로 반드시 암호를 설정하는 것이 좋습니다.",
	"The admin account can change all router settings. To keep your router secure, you should give the admin account a strong password.":"관리자 계정으로 공유기의 모든 설정을 변경할 수 있습니다. 공유기의 보안을 위해 강력한 비밀번호를 설정하시기 바랍니다.",
	"Please enter an NTP server to use.":"사용 할 NTP 서버를 입력하여 주십시오.",
	"Text field contains illegal characters.":"텍스트 입력에 잘못된 문자가 포함되어 있습니다.",
	"Please enter a valid IPv6 address range (e.g., 2001::1-2001::2)":"사용 할 IPv6 주소 범위를 입력하여 주십시오. (예, 2001::1-2001::2)",
	"Invalid character":"사용 할 수 없는 문자",
	"Not Available":"사용 할 수 없습니다",
	"There are no devices available":"사용 할 수 있는 장치가 없습니다",
	"Please enter a valid e-mail.":"사용 할 이메일 주소를 입력하여 주십시오.",
	"Pictures":"사진",
	"Search Photos...":"사진 검색 ...",
	"The Private Browsing feature of Safari is incompatible with this device's interface. You will need to disable Private Browsing to log in.":"사파리의 개인 정보 보호 브라우징 기능이 장치의 인터페이스와 호환되지 않습니다. 로그인 할 개인 정보 보호 브라우징을 비활성화 해야합니다.",
	"Delete":"삭제",
	"Please select a file to delete.":"삭제 할 파일을 선택하십시오.",
	"Status:":"상태 :",
	"Stateful DHCPv6":"Stateful DHCPv6",
	"Create a New User":"새 사용자 만들기",
	"Create New User":"새 사용자를 만듭니다",
	"The new settings have been saved.":"새로운 설정이 저장되었습니다.",
	"New Firmware Date":"최신 펌웨어 날짜",
	"Download New Firmware":"최신 펌웨어 다운로드",
	"Download New Firmware ":"최신 펌웨어 다운로드",
	"Check for New Firmware":"최신 펌웨어 확인",
	"Check For New Firmware":"최신 펌웨어 확인",
	"New Folder":"새 폴더",
	"Create a new session":"새로운 세션 생성",
	"New firmware available":"새로운 펌웨어가 있습니다.",
	"New Firmware Version":"새로운 펌웨어 버전",
	"A new firmware is available! Do you want to download and upgrade the firmware?":"새로운 펌웨어를 사용 할 수 있습니다. 펌웨어 업그레이드를 진행하시겠습니까?",
	"Documents":"문서",
	"Select Server Name":"서버 이름 선택",
	"Server Address":"서버 주소",
	"Please enter a server address":"서버 주소를 입력 해주십시오 ",
	"Subnet Mask":"서브넷 마스크",
	"Mask":"서브넷 마스크",
	"Please enter a subnet mask.":"서브넷 마스크를 입력하십시오.",
	"Subnet Prefix Length":"서브넷 Prefix 길이",
	"Service Name":"서비스 이름",
	"Select":"선택",



	"SELECT":"선택",
	"You can block a device from accessing your network at all times or according to a schedule by using the Block dropdown box.":"선택항목을 변경하여 특정 단말에 대한 접속을 차단 할 수 있습니다.",
	"You can block a device from accessing your network completely.":"선택항목을 변경하여 특정 단말에 대한 접속을 차단하실 수 있습니다.",
	"Settings":"설정",
	"Setting and registering your router with mydlink will allow you to use its mydlink cloud services features, including online access and management of your router through the mydlink portal website.":"Mydlink 서비스에 공유기를 등록하면, Mydlink 포털 웹사이트 및 스마트기기용 Mydlink 어플을 통해 온라인으로 공유기의 관리를 포함하여 Mydlink 클라우드 서비스 기능을 사용할 수 있습니다.",
	"Creating a mydlink account and registering your router with mydlink will allow you to remotely montior and manage your network on your smartphone or tablet, as well as through the secure web portal. It also allows you to plug in a USB drive and access the stored files from anywhere in the world through iOS and Android apps as well as the web browser on your computer.":"Mydlink 계정을 생성하고 공유기에 가입한 Mydlink 계정을 등록하면, Mydlink 포털 웹사이트 및 스마트기기용 Mydlink 어플을 통해 온라인으로 공유기의 관리를 포함하여 Mydlink 클라우드 서비스 기능을 사용할 수 있습니다.",
	"Your changes are being saved, please wait...":"설정값을 저장하고 있습니다. 잠시만 기다려 주십시오...",
	"Your changes are being saved.":"설정을 저장하고 있습니다.",
	"Your settings are being saved.":"설정을 저장하고 있습니다.",
	"Your changes are being saved, and the device will need to reboot.":"설정을 저장하고 있습니다. 일부 설정은 장비가 재부팅된 이후에 적용됩니다.",
	"Please check your settings and try again.":"설정을 확인하고 다시 시도하십시오.",
	"Reset to Unconfigured":"설정하지 않은 상태로 리셋",
	"Go to settings":"설정화면",
	"Install":"설치",
	"Setup Wizard":"설치 마법사",
	"Wizard":"설치 마법사",
	"Setup Complete":"설치 완료",
	"Last Name":"성",
	"Reboot success!":"재부팅에 성공했습니다!",
	"Session":"세션",
	"Guest":"게스트",
	"Manual Configuration":"수동 구성",
	"Manual Time Confuguration":"수동으로 시간 구성",
	"Manual Time Configuration":"수동으로 시간 구성",
	"Upgrade Manually":"수동으로 업그레이드",
	"Received":"수신",
	"Received (Rx)":"수신 (RX)",
	"Received (RX)":"수신 (RX)",
	"On demand":"수요",
	"Wednesday":"수요일",
	"Scanning":"검색 중",
	"SCAN":"검색",
	"Scan":"검색",
	"Some features, such as the firewall and website filters, can be turned on or off based on a schedule. One common use of schedules is to control access to the Internet by a specified device during specified time periods.":"웹사이트 필터나 방화벽 같은 일부 기능들은 스케줄에 따라 켜거나 끌 수 있습니다. 일반적으로 특정 단말에 대해 정해진 시간 동안에 인터넷 접속을 제어하는데 사용됩니다.",
	"Send on Schedule":"스케줄 발송",
	"Enable Storage Remote Access":"스토리지 원격 액세스 활성화",
	"Speaker":"스피커",
	"hours":"시간",
	"Time":"시간",
	"Hour":"시",
	"Hour/ Minute":"시간 / 분",
	"(Hour/ Minute)":"시간 / 분",
	"Time Confuguration":"시간 구성",
	"Time Configuration":"시간 구성",
	"Time & Schedule":"시간 및 일정",
	"Connection Up Time":"연결 유지 시간",
	"Connection Uptime":"연결 유지 시간",
	"Time Zone":"시간대",
	"System Admin":"시스템 관리자",
	"System Log":"시스템 로그",
	"SysLog Settings":"시스템 로그 설정",
	"System Time":"시스템 시간",
	"Fail":"실패",
	"No, I want to create a new mydlink account.":"아니오, 새로운 mydlink 계정을 등록하겠습니다.",
	"No, I want to create a new mydlink account":"아니오, 새로운 mydlink 계정을 등록하겠습니다.",
	"No.":"아니오.",
	"Type the characters you see in the picture below.":"아래 보이는 그림문자를 입력하여 주십시오.",
	"Below is a summary of your Wi-Fi security and device password settings.Please take a note of your settings and save your configuration.":"아래는 공유기에 저장된 Wi-Fi 설정 및 관리자 페이지 접속 비밀번호입니다. 기억하시기 바라며 '다음'을 눌러주십시오.",
	"Drag the device cards above to the Prioity boxes below.":"아래의 Priority 상자에 위의 장치 카드를 드래그합니다.",
	"Drag the device cards above to the priority boxes below.":"아래의 Priority 상자에 위의 장치 카드를 드래그합니다.",
	"Username/Password Connection (PPPoE)":"사용자 이름 / 패스워드 연결 (PPPoE)",
	"Unsecured":"안전하지 않음",
	"Password":"암호",
	"Password length":"암호 길이",
	"A password is required to join":"암호를 입력해야합니다",
	"The password field cannot be blank.,":"암호는 비워 둘 수 없습니다.,",
	"Password is incorrect.":"암호가 잘못되었습니다.",
	"The password must contain at least 8 characters. You will need to join your Wi-Fi network using this password.":"암호는 8 자 이상 포함되어야합니다. 이 암호를 사용하여 Wi-Fi 네트워크에 연결해야합니다.",
	"The password must contain at least 8 characters":"암호는 8자 이상 입력 되어야 합니다.",
	"Access":"액세스",
	"Access Path":"액세스 경로",
	"No new firmware":"새로운 펌웨어가 없습니다",
	"No language pack installed.":"언어 팩이 설치되어 있지 않습니다.",
	"Language":"언어",
	"Language Pack Imformation":"언어 팩 정보",
	"Language Pack Information":"언어 팩 정보",
	"Add a Language Pack":"언어 팩 추가",
	"Uplink Router":"업링크 공유기",
	"Upgrade":"업그레이드",
	"Upgrading":"업그레이드 중",
	"Upgrading...":"업그레이드 중...",
	"The Upgrade process cannot be cancelled, and this page must stay open until the the process is complete!":"업그레이드 프로세스는 취소 할 수 없으며 프로세스가 완료 될 때까지 이 페이지를 유지해야합니다!",
	"Before performing an upgrade, be sure to save the current configuration from the Management-System screen. Do you still want to upgrade?,":"업그레이드를 수행하기 전에, 관리 시스템 화면에서 현재 구성을 저장해야합니다. ​​업그레이드 하시겠습니까?",
	"Upload":"업로드",
	"The uploaded file may not be correct. You may have uploaded a file that is not intended for this router, or the uploaded file may be corrupted.,":"업로드 된 파일이 올바르지 않습니다. 해당 공유기용 파일이 아닙니다. 파일을 강제로 업로드 하게 되면, 기기가 손상 될 수 있습니다.",
	"If the uploaded file is correct, it is possible that the router may be too busy to properly receive it right now. In this case, please try the upload again.,":"업로드 된 파일이 올바른 경우에도, 공유기가 정상적으로 수신하기에 실패 할 가능성도 있습니다. 이 경우, 다시 업로드를 시도하십시오.",
	"The uploaded firmware file may be corrupted; please check the file or try downloading it again.":"업로드 된 펌웨어 파일이 손상 될 수 있습니다. 파일을 재확인하거나 다시 다운로드를 시도하십시오.",
	"None":"없음",
	"Please select a folder to allow access to.":"액세스를 허용 할 폴더를 선택하십시오.",
	"Please choose one site to connect to.":"연결 할 하나의 사이트를 선택하세요.",
	"Air Play":"Air Play",
	"click here.":"본 항목을 클릭하여 주십시오.",
	"Please note that making changes here may require you to change the wireless settings on your other devices.,":"여기에서 변경하는 내용은 다른 기기의 무선 설정을 변경해야 할 수도 있습니다.,",
	"Here, you can see a list of all devices connected through Wi-Fi. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.":"여기에서, Wi-Fi를 통해 연결된 모든 장치의 목록을 볼 수 있습니다. 이것에 대한 더 많은 정보를 보려면, 장치를 쉽게 식별 할 수 있도록 이름을 지정하는 연필 아이콘 또는 장치를 클릭하십시오. 블록 드롭 다운 상자를 사용하여 항상 네트워크에 액세스하거나 일정에 따라에서 장치를 차단할 수 있습니다.",
	"Here, you can set up various firewall features to protect your network from attacks. You can click on the DMZ, IPv4 Rules, and IPv6 Rules buttons to see the settings for that feature.":"여기에서, 외부의 해킹 공격으로부터 네트워크를 보호하기 위해 다양한 방화벽 기능을 설정할 수 있습니다. 해당 기능에 대한 설정을 확인합니다 DMZ, IPv4의 규칙 및 IPv6 규칙 단추를 클릭 할 수 있습니다.",
	"Your router's high-performance firewall feature continuously monitors Internet traffic, protecting your network and connected devices from malicious Internet attacks.":"공유기의 고성능 방화벽은 지속적으로 인터넷 트래픽을 모니터링하여 인터넷 공격으로부터 네트워크와 연결된 클라이언트를 보호합니다.",
	"Here, you can configure the Wi-Fi network settings for your router.":"여기에서, 공유기의 Wi-Fi 네트워크 설정을 구성 할 수 있습니다.",
	"Here, you can configure the various storage sharing features of your router. The DLNA server allows you to stream stored pictures, music, and video to another DLNA-compatible device on your network. Web File Access allows you to use a web browser to access stored files from a PC connected to your network.":"여기에서, 공유기에 다양한 스토리지 공유 기능을 구성 할 수 있습니다.DLNA 서버는 네트워크의 다른 DLNA 호환 장치에 저장된 사진, 음악 및 비디오를 스트리밍 할 수 있습니다. 웹 파일 액세스는 네트워크에 연결된 PC에서 저장된 파일을 액세스 할 웹 브라우저를 사용할 수 있습니다.",
	"Here, you can see a list of all devices connected to your Wi-Fi network. Click on a device's pencil icon for further options.":"여기에서, Wi-Fi에 연결된 모든 장치의 목록을 볼 수 있습니다. 추가 옵션에 대해 확인하려면 장치의 연필 아이콘을 클릭합니다.",
	"Here, you can see a list of all devices connected to your Wi-Fi Guest Zone. Click on a device's pencil icon for further options.":"여기에서, 게스트 존 Wi-Fi에 연결된 모든 장치의 목록을 볼 수 있습니다. 추가 옵션에 대해 확인하려면 장치의 연필 아이콘을 클릭합니다.",
	"Here, you can configure the local network settings for your router, including the IP address you use to access this configuration interface. Please note that if you change this IP address, you will need to use the new IP to access this interface.":"이 메뉴에서는 펌웨어에 접속하기 위해 사용하는 IP 주소를 포함하여 공유기의 로컬 네트워크 설정을 변경 할 수 있습니다. LAN IP 주소를 변경하는 경우, 펌웨어에 접속하려면 새로운 IP를 사용해야 합니다.",
	"Connect":"연결",
	"Connected":"연결 됨",
	"Disconnected":"연결 끊김",
	"Connection Type":"연결 유형",
	"Connection type":"연결 유형",
	"Connecting...":"연결 중 ...",
	"Connected Clients":"연결된 단말",
	"Disonnected":"연결이 끊김",
	"Connecting":"연결 중…",
	"Operator":"오퍼레이터",
	"Video":"비디오",
	"Yes":"예",
	"Reserved IP":"예약 된 IP",
	"Reserve IP":"예약 된 IP",
	"Schedule":"스케줄",
	"Audio Renderer":"오디오 렌더러",
	"Please enter a name for your Audio Renderer.":"오디오 렌더¬의 이름 입력하­시오.",
	"On Demand":"수요",
	"Please enter a Wi-Fi Name(SSID).":"Wi-Fi 이름 (SSID)을 입력하십시오.",
	"External Port":"외부 포트",
	"Remote HTTPS Port":"원격 HTTPS 포트",
	"Remote IPv4 Address":"원격 IPv4 Address (IPv4 주소)",
	"Remote IPv6 Address":"원격 IPv6 Address (IPv6 주소)",
	"Remote Admin Inbound Filter":"원격 관리 인바운드 필터",
	"Remote Admin Port":"원격 관리 포트",
	"Enable Remote Management":"원격 관리 설정",
	"Remote Access":"원격 액세스",
	"Remote Access Port":"원격 액세스 포트",
	"Monday":"월요일",
	"Website URL/Domain":"웹 사이트 URL / 도메인",
	"The Website Filter option allows you to set up a list of Web sites you would like to allow or deny through your network. To use this feature, you must also select the \"Apply Web Filter\" checkbox in the Access Control section.":"웹 필터 기능을 사용하면 네트워크에 있는 장치의 웹사이트 접속을 허용 또는 거부 할 수 있습니다. 이 기능을 사용하려면 엑세스 제어 목록에서 “거부“ 또는 “허용“을 선택해 주고 웹 사이트 URL/도메인 규칙에 추가해야 합니다.",
	"The website filters feature allows rules to be set that restrict access to a specified web address (URL) or blocks specified keywords in the URL. You can use Website Filter to restrict access to potentially harmful and inappropriate websites.":"웹 사이트 필터 허용 규칙 설정은 웹사이트 주소(URL) 또는 URL의 특정 키워드로 설정이 가능합니다. 해당 기능을 사용하면 문제 발생의 요지가 있는 특정 웹사이트 사용을 막을 수 있습니다.",
	"Web File Access":"웹 파일 액세스",
	"Web File Access Login":"웹 파일 액세스 로그인",
	"Log in to the web file access Server":"웹 파일 액세스 서버 로그인",
	"Web File Access allows you to use a web browser to remotely access files store on an SD card or USB storage drive plugged into the router.":"웹 파일 액세스는 원격으로 공유기에 연결 된 SD카드 또는 USB 저장 드라이브 같은 파일 저장소에 액세스하기 위해 웹 브라우저를 사용할 수 있습니다.",
	"Website Filter":"웹사이트 필터",
	"Windows File Sharing":"윈도우 파일 공유",
	"Windows File Sharing (SAMBA)":"윈도우 파일 공유(SAMBA)",
	"Dynamic PPPoE ":"유동 PPPoE",
	"Here, you can see a list of all devices connected through an Ethernet cable. Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.":"유선으로 연결되어 있는 장치 목록입니다. 해당 장치를 클릭하시면 자세한 정보를 보실 수 있습니다. 장치 정보를 변경하려면, [연필] 아이콘을 클릭하여 입력하여 주십시오. 또한, 선택항목을 변경하여 해당 장치의 접속을 차단 할 수 있습니다.",
	"Click on a device to view more information about it, or click on the pencil icon to give the device a name to make it easy to identify. You can block a device from accessing your network always or according to a schedule by using the Block dropdown box.":"장치를 클릭하여 더 자세한 정보를 확인 할 수 있습니다. 장치 정보를 변경하려면, [연필] 아이콘을 클릭하여 입력하여 주십시오. 또한, 선택항목을 변경하여 해당 장치의 접속을 차단 할 수 있습니다.",
	"Type":"유형",
	"Please enter a valid IP address range. (e.g. 1.1.1.1-1.1.1.2)":"유효한 IP 주소 범위를 입력하십시오. (예 : 1.1.1.1-1.1.1.2)",
	"Please enter a valid IP address. (e.g. 192.168.0.1)":"유효한 IP 주소를 입력 해주십시오. (예 : 192.168.0.1)",
	"Please enter a valid IP address. (e.g. 255.255.255.0)":"유효한 IP 주소를 입력 해주십시오. (예 : 255.255.255.0)",
	"Please enter a valid IPv6 address. (e.g. 2001::1)":"유효한 IPv6의 주소를 입력 해주십시오. (예 : 2001 :: 1)",
	"Please enter a valid IPv6 IP address. (e.g. 2001::1)":"유효한 IPv6의 IP 주소를 입력 해주십시오. (예 : 2001 :: 1)",
	"Please enter a valid gateway address. (e.g. 192.168.0.1)":"유효한 게이트웨이 주소를 입력 해주십시오. (예 : 192.168.0.1)",
	"Please enter a valid netmask. (e.g. 255.255.255.0)":"유효한 넷 마스크를 입력하십시오. (예 : 255.255.255.0)",
	"Please enter a valid destination network IP address. (e.g. 2001::)":"유효한 대상 네트워크의 IP 주소를 입력하십시오. (예 : 2001::)",
	"Please enter a valid username and password.":"유효한 사용자 이름과 암호를 입력하십시오.",
	"Please enter a valid port number.":"유효한 포트 번호를 입력하십시오.",
	"Please enter a valid port range. (e.g. 1000-1001)":"유효한 포트 범위를 입력하십시오. (예 : 1000-1001)",
	"Music":"음악",
	"Application Level Gateway (ALG) Configuration":"응용 프로그램 레벨 게이트웨이 (ALG) 구성",
	"Please Take a note of the following summary of your Wi-Fi Security setting for furture reference":"나중에 참조 할 수 있도록 무선 인터넷 보안 설정 등 다음과 같은 요약 정보를 확인하시기 바랍니다",
	"Scanning for Wi-Fi hotspot networks…":"Wi-Fi 핫스팟 네트워크를 검색 ...",
	"To set up this conncetion you will need to have a complete list of IP information by your Internet Service Provider. If you have a Static IP connection and do not have this information, please contact your ISP.":"이 연결을 설정하려면 인터넷 서비스 공급자를 통해 전체적인 IP 정보의 목록이 필요합니다. 고정 IP 연결이기 때문에 이 정보가 없는 경우, ISP에 문의하십시오.",
	"Use this page to configure the local network settings for your router, including the IP address you use to access this configuration interface. Please note that if you change this IP address, you will need to use the new IP to access this interface.":"이 메뉴에서는 펌웨어에 접속하기 위해 사용하는 IP주소를 포함하여 공유기의 로컬 네트워크 설정을 변경할 수 있습니다. LAN IP 주소를 변경하는 경우, 펌웨어에 접속하려면 변경한 새로운 IP를 사용해야 합니다.",
	"Use this section to configure the network settings for your device. You can enter a name for your device in the management link field, and use the link to access web UI in a web browser. Recommend to change the management link if there are more than one D-Link devices within the network.":"이곳에서 장치에 대한 네트워크 설정을 구성할 수 있습니다. 장치의 관리 링크에 설정한 이름으로 웹 브라우저에서 웹 UI에 접속할 수 있습니다. 네트워크 내에 다른 D-Link 장치가 있다면 관리 링크를 변경해서 사용하시기 바랍니다.",
	"Please enter a name for this rule.":"이 규칙에 대한 이름을 입력 해주세요.",
	"This wizard is designed to assist you in your Wi-Fi network setup. It will guide you through step-by step instructions on how to set up your Wi-Fi network and how to make it secure.":"이 마법사는 Wi-Fi 네트워크 설정에 도움을 주도록 만들어졌습니다. 단계별 안내를 통해 Wi-Fi 네트워크를 설정하는 방법과 보안을 설정 합니다.",
	"This wizard will guide you through a step-by-step process to configure your new D-Link device.":"마법사의 단계별 과정을 통해 D-Link 장치를 구성하는 방법을 여러분에게 안내 할 것입니다.",
	"To setup this Internet connection, you will need to have a User Name from your InternetService Provider. If you do not have this information, please contact your ISP.":"이 인터넷 연결을 설정하려면, 고객님의 인터넷 서비스 공급자의 사용자 이름이 필요합니다. 이 정보가없는 경우, ISP에 문의하십시오.",
	"To setup this Internet connection, you will need to have a User Name from your Internet Service Provider. If you do not have this information, please contact your ISP.":"이 인터넷 연결을 설정하려면, 고객님의 인터넷 서비스 공급자의 사용자 이름이 필요합니다. 이 정보가없는 경우, ISP에 문의하십시오.",
	"This device is mydlink-enabled, which allows you to remotely monitor and manage your network through the mydlink.com website, or through the mydlink mobile app.":"이 장치는 mydlink  웹사이트 또는 모바일용 mydlink 어플을 통해 네트워크 상태를 모니터링하고 관리할 수 있습니다.",
	"This firmware is the latest version.":"최신 펌웨어로 업그레이드 되어 있습니다.",
	"This page lets you configure a Wi-Fi Guest Zone. Wi-Fi Guest Zones are Wi-Fi networks that are separate from your normal ones, and use different Wi-Fi Network Names and passwords. Users connected to a Guest Zone cannot communicate or detect devices on your normal network unless the Access Local Service option is enabled. Guest Zones are useful to give guests Internet access without allowing them to access your own devices on your network.":"이 메뉴에서 Wi-Fi 인터넷 게스트 존을 활성화 할 수 있습니다. 게스트존에 인터넷 접속전용 옵션이 활성화 되어 있다면 연결된 사용자는 홈 네트워크의 내부장치를 검색 할 수 없습니다. ",
	"This page lets you configure a Wi-Fi Guest Zone. Wi-Fi Guest Zones are Wi-Fi networks that are separate from your normal ones, and use different Wi-Fi Network Names and passwords. Users connected to a Guest Zone cannot communicate or detect devices on your normal network unless the Routing Between Zones option is enabled. Guest Zones are useful to give guests Internet access without allowing them to access your own devices on your network.":"이 메뉴에서 Wi-Fi 인터넷 게스트 존을 활성화 할 수 있습니다. 게스트존에 인터넷 접속전용 옵션이 활성화 되어 있다면 연결된 사용자는 홈 네트워크의 내부장치를 검색 할 수 없습니다.",
	"This page shows you your current firmware version and language pack, and allows you to check for and download new firmware. After downloading the firmware, you can then upgrade it by using the buttons below. If you are using a language pack, we recommend that you also get the latest version of the language pack when upgrading the firmware to ensure that any changes in the interface are shown correctly. ":"이 메뉴에서는 공유기의 현재 펌웨어 버전과 날짜를 확인할 수 있습니다. 새로운 펌웨어를 다운로드 할 수 있으며 업그레이드를 할 새 펌웨어를 mydlink.co.kr에서 다운받아서 선택한 후 아래의 버튼으로 수동업그레이드를 할 수도 있습니다. 공유기 사용에 문제가 있을 때, 새로운 펌웨어로 업그레이드를 하는 것이 좋습니다.",
	"This page shows you your current firmware version and language pack, and allows you to check for and download new firmware. After downloading the firmware, you can then upgrade it by using the buttons below. If you are using a language pack, we recommend that you also get the latest version of the language pack when upgrading the firmware to ensure that any changes in the interface are shown correctly.":"이 메뉴에서는 공유기의 현재 펌웨어 버전과 날짜를 확인할 수 있습니다. 새로운 펌웨어를 다운로드 할 수 있으며 업그레이드를 할 새 펌웨어를 mydlink.co.kr에서 다운받아서 선택한 후 아래의 버튼으로 수동업그레이드를 할 수도 있습니다. 공유기 사용에 문제가 있을 때, 새로운 펌웨어로 업그레이드를 하는 것이 좋습니다.",
	"Your router can automatically detect firmware updates, but requires your authorization to install them. It is also possible to check for new firmware manually, upgrade firmware from a local file.":"이 메뉴에서는 공유기의 현재 펌웨어 버전과 날짜를 확인할 수 있습니다. 새로운 펌웨어를 다운로드 할 수 있으며 업그레이드를 할 새 펌웨어를 mydlink.co.kr에서 다운받아서 선택한 후 아래의 버튼으로 수동업그레이드를 할 수도 있습니다. 공유기 사용에 문제가 있을 때, 새로운 펌웨어로 업그레이드를 하는 것이 좋습니다.",
	"This page shows you your current firmware version and language pack, and allows you to check for and download new firmware. After downloading the firmware, you can then upgrade it by using the buttons below. If you are using a language pack, we recommend that you also get the latest version of the language pack when upgrading firmware to ensure that any changes in the interface are shown correctly.":"이 메뉴에서는 공유기의 현재 펌웨어 버전과 날짜를 확인할 수 있습니다. 새로운 펌웨어를 다운로드 할 수 있으며 업그레이드를 할 새 펌웨어를 mydlink.co.kr에서 다운받아서 선택한 후 아래의 버튼으로 수동업그레이드를 할 수도 있습니다. 공유기 사용에 문제가 있을 때, 새로운 펌웨어로 업그레이드를 하는 것이 좋습니다.",
	"This page allows you to define custom routes to define how data traffic is moved around your network.":"이 메뉴에서는 데이터 트래픽이 네트워크를 통해 이동하는 경로를 사용자가 정의 할 수 있습니다니다.",
	"Once connected to the Internet, your router automatically builds routing tables that determine where traffic should be sent. Static routes can override this process, allowing traffic to be directed to a specific client or location.":"이 메뉴에서는 데이터 트래픽이 네트워크를 통해 이동하는 방법과 설정 된 사용자의 경로를 정의 할 수 있습니다.",
	"This page allows you to set the router's internal system clock. You can set the time manually, or automatically through a time server.":"공유기의 시간 설정은 시스템 로그와 특정 스케줄 기능에 사용됩니다. 날짜와 시간은 인터넷 시간 서버와 동기화 하거나, 수동으로 설정 할 수 있습니다.",
	"Your router's internal clock is used for data logging and schedules for features. The date and time can be synchronized with a public time server on the Internet, or set manually.":"이 메뉴에서는 공유기의 내부 시스템 시간을 설정 할 수 있습니다.고객님의 NTP 서버를 통해 수동 또는 자동으로 시간을 설정 할 수 있습니다.",
	"This page lets you save or restore your router's current settings. You can also reset your router to the factory defaults or reboot the router. Please note that resetting your router will erase all settings and rules you have created.":"이 메뉴에서 공유기의 현재 설정을 저장하거나 복원 할 수 있습니다. 또한 공장 기본값으로 공유기를 초기화하거나 재부팅 할 수도 있습니다. 공유기를 초기화하게 되면 모든 설정과 규칙이 삭제된다는 점에 유의하시기 바랍니다.",
	"This page lets you configure a Wi-Fi Guest Zone, which lets you share Internet access with guests on a separate Wi-Fi network. Guests will be prevented from accessing devices on your home network unless Allow Local Access is enabled.":"이 메뉴에서는 별도의 Wi-Fi 네트워크에 연결 된 게스트의 ​인터넷 액세스 권한을 줄 있습니다. 로컬 액세스가 비활성화되어 허용되지 않는다면 게스트는 홈 네트워크에 있는 장치에 액세스 할 수 없게됩니다.",
	"This page gives you various statistics about data transmitted and received by your router through the Internet, on your wired network (LAN), and through your wireless networks.":"이 메뉴에서는 유선(LAN)또는 무선 네트워크를 통해 사용한 공유기의 송수신 데이터에 대한 통계를 볼 수 있습니다.",
	"This page gives you various statistics about data transmitted and received by your AP through the internet, and through your wireless networks.":"이 메뉴에서는 인터넷을 통해 AP가 무선 네트워크를 통해 전송 및 수신한 데이터에 대한 다양한 통계 정보를 제공합니다.",
	"This page allows you to enable logging of system events to a SysLog server, or to e-mail the log to you according to a schedule or when the log is full.":"이 메뉴에서는 로그가 일정 이상 쌓이거나 스케줄 설정에 따라 Syslog 서버를 통해 시스템 이벤트 로그나 전자메일로 해당 내용을 보낼 수 있는 기능입니다.",
	"On-board diagnostics run continually in the background to monitor the health of your router. The results are recorded in the system log if it is enabled. This info can be used to diagnose common problems or help Customer Support resolve issues more quickly.":"이 메뉴에서는 로그가 일정 이상 쌓이거나 스케줄 설정에 따라 Syslog 서버를 통해 시스템 이벤트 로그나 전자메일로 해당 내용을 보낼 수 있는 기능입니다.",
	"This page shows you your current firmware version, and allows you to check for and download new firmware. After downloading the firmware, you can then upgrade it by using the buttons below.":"이 메뉴에서는 현재 펌웨어 버전을 확인 할 수 있고, 새로운 펌웨어를 다운로드 할 수 있습니다. 펌웨어를 다운로드 후,아래의 버튼을 사용하여 업그레이드 할 수 있습니다.",
	"This page lets you save your router's current settings to a file, restore your settings from a file, restore your router to factory default settings, or reboot the device. Please note that restoring the settings to the factory defaults will erase all settings, including any rules you have created.":"이 메뉴에서는 공유기의 현재 설정을 저장하거나 복원 할 수 있습니다. 또한 공장 기본값으로 공유기를 초기화하거나 재부팅 할 수도 있습니다. 공유기를 초기화하게 되면 모든 설정과 규칙이 삭제된다는 점에 유의하시기 바랍니다.",
	"This page lets you enable and configure a Wi-Fi Guest Zone. Users connected to a Guest Zone cannot communicate or detect devices on your normal network unless Internet Access Only iis disabled under Home Network Access.":"이 메뉴에서는 Wi-Fi 인터넷 게스트존을 활성화하고 구성 할 수 있습니다. 고객 영역에 연결 된 사용자가 내부 통신 및 홈 네트워크 엑세스에 접근하지 않도록 하고 인터넷 엑세스만 가능하도록 설정할 수 있습니다.",
	"This folder has already been added.":"이 폴더는 이미 추가 되었습니다.",
	"This will cause all current settings to be lost.,":"현재의 모든 설정이 손실 될 수 있습니다.",
	"Ethernet Device":"이더넷 장치",
	"err_address_Check": "유효한 IP 주소를 입력 해주십시오. (예 : 192.168.0.1)",
	"DENY clients access to ONLY these sites":"설정 된 사이트에 접속 거부",
	"Username":"사용자 이름",
	"First Name":"이름",
	"Name":"이름",
	"Username:(optional)":"사용자 이름 : (선택 사항)",
	"Please enter a username.":"사용자 이름을 입력하세요.",
	"E-mail Log When Full or On Schedule":"이메일 로그의 전체 또는 스케줄",
	"Enable E-mail Notification":"이메일 알림을 활성화",
	"To E-mail Address":"받는 이메일 주소",
	"Email or password field is required.":"이메일 혹은 비밀번호를 입력하여 주십시오.",
	"From E-mail Address":"보내는 이메일 주소",
	"This IP address is already reserved for another device.":"IP 주소가 이미 다른장치에서 예약할당 중 입니다.",
	"You may now use mydlink service with this device.":"이제 이 장치는 mydlink 서비스를 사용할 수 있습니다.",
	"Enable Authentication":"인증 사용",
	"Authentication Protocol":"인증 프로토콜",
	"Internet":"인터넷",
	"Internet ":"인터넷",
	"Internet(WAN)":"인터넷 (WAN)",
	"Choose this option if your Internet Setup Provider provided you with IP Address information that has to be manually configured.":"고정 IP를 할당받아서 사용하는 회사나 학교, 공공기관인 경우 이 옵션을 선택합니다.",
	"Configure Your Internet Connection":"인터넷 연결 구성",
	"Please select your Internet connection type below":"인터넷 연결 유형을 선택하세요",
	"Please select your Internet connection type below:":"인터넷 연결 유형을 선택하세요",
	"Use this section to configure your Internet Connection type. There are several connection types to choose from Static IP, DHCP, PPPoE, PPTP, L2TP, and DS-Lite. If you are unsure of your connection method, please contact your Internet Service Provider. Note:  If using the PPPoE option, you will need to remove or disable any PPPoE client software on your computers.":"인터넷 연결 유형을 확인 후 설정하려면 이 메뉴를 이용합니다. 고정 IP, 동적 IP (DHCP), PPPoE, PPTP, L2TP 및 DS-Lite 중 해당하는 연결 유형을 선택해주세요. 연결 유형을 모를 경우 ISP 업체에 문의 후 확인 해주시기 바랍니다. 참고: PPPoE의 연결 유형을 사용하는 경우, PC에 구성되어 있는 PPPoE 클라이언트 소프트웨어를 제거하거나 사용하지 않도록 설정해야합니다.",
	"Use this section to configure your Internet Connection type. There are several connection types to choose from Static IP, DHCP, PPPoE, PPTP, L2TP and DS-Lite. If you are unsure of your connection method, please contact your Internet service provider. Note: If using the PPPoE option, you will need to remove or disable any PPPoE client software on your computers.":"인터넷 연결 유형을 확인 후 설정하려면 이 메뉴를 이용합니다. 고정 IP, 동적 IP (DHCP), PPPoE, PPTP, L2TP 및 DS-Lite 중 해당하는 연결 유형을 선택해주세요. 연결 유형을 모를 경우 ISP 업체에 문의 후 확인 해주시기 바랍니다. 참고: PPPoE의 연결 유형을 사용하는 경우, PC에 구성되어 있는 PPPoE 클라이언트 소프트웨어를 제거하거나 사용하지 않도록 설정해야합니다.",
	"Use this section to configure your Internet Connection profiles. If you are not sure what settings to use, please contact your Internet Service Provider.":"인터넷 연결 프로파일을 구성하려면 이 섹션을 사용합니다. 고객님께서사용하는 설정이 확실하지 않은 경우, 인터넷 서비스 공급자에게 문의하십시오.",
	"Use this section to configure your Internet Connection profiles. If you are not sure what settings to use, please contact your Internet Service Provider. ":"인터넷 연결 프로파일을 구성하려면 이 섹션을 사용합니다. 고객님께서사용하는 설정이 확실하지 않은 경우, 인터넷 서비스 공급자에게 문의하십시오.",
	"Checking Internet connectivity":"인터넷 연결 확인",
	"Checking Internet Connectivity":"인터넷 연결 확인",
	"Internet Disconnected":"인터넷 연결끊김",
	"Internet Connected":"인터넷 연결됨",
	"Detecting Internet connection":"인터넷 연결을 감지하는 중",
	"Detecting Internet Connection":"인터넷 연결을 감지하는 중",
	"Choose this option if your Internet connection reguires a username and passowrd to get online. Most DSL modems use this connection type of connction.":"통신사 아이디와 암호가 필요한 경우에 여기를 선택합니다.",
	"Choose this option if your Internet connection reguires a username and passowrd to get online. Most DSL modems use this connection type of connection.":"통신사 아이디와 암호가 필요한 경우에 여기를 선택합니다.",
	"Choose this if your Internet connection automatically provides you with an IP Address. Most Cable Modems use this type of connection.":"인터넷 연결이 자동으로 IP 주소를 제공하는 경우 이 옵션을 선택합니다. 대부분의 케이블 모뎀이나 광랜이 이런 경우입니다.",
	"Internet Access Only":"내부 통신 불가",
	"Internet Profiles":"인터넷 프로필",
	"Internet Profiles ":"인터넷 프로필",
	"Internet Profiles are networks you want the device to remember and reconnect to in the future. Profiles are created automatically the first time you connect to a particular network, and some profiles may require additional information from your Internet service provider.":"인터넷 프로필은 장치를 기억하고 나중에 다시 연결하려는 네트워크입니다. 프로필은 특정 네트워크에 연결해서 자동으로 생성 됩니다. 일부 프로파일은 인터넷 서비스 제공 업체에서 추가 정보를 요구할 수 있습니다.",
	"Internet Profiles are networks you want the device to remember and reconnect to in the future. Profiles are created automatically the first time you connect to a particular network, and some profiles may require additional information from your Internet service provider. ":"인터넷 프로필은 장치를 기억하고 나중에 다시 연결하려는 네트워크입니다. 프로필은 특정 네트워크에 연결해서 자동으로 생성 됩니다. 일부 프로파일은 인터넷 서비스 제공 업체에서 추가 정보를 요구할 수 있습니다.",
	"Interface":"인터페이스",
	"Enable Daylight Saving":"일광 절약 가능",
	"compatibility for some DHCP Clients":"일부 DHCP 클라이언트에 대한 호환성",
	"Some firmware upgrades reset the router's configuration options to the factory defaults.,":"일부 펌웨어는 업그레이드 이후 공장 초기값으로 자동 구성이 됩니다.",
	"Sunday":"일요일",
	"On Schedule":"스케줄",
	"The Schedule configuration option is used to manage schedule rules for various firewall and parental control features.":"스케줄 설정 옵션은 관리 스케줄 규칙에 따라 다양한 방화벽 및 보호 기능을 사용 할 수 있습니다.",
	"Read/Write":"읽기/쓰기",
	"Read Only":"읽기 전용",
	"Authentication":"인증",
	"Parental Control":"자녀 보호",
	"Auto":"자동",
	"Auto (10/100/1000 Mbps)":"자동 (10/100/1000 Mbps)",
	"Auto(PAP+CHAP)":"자동 (PAP + CHAP)",
	"Autoconfiguration (SLAAC/DHCPv6)":"자동 구성(SLAAC/DHCPv6)",
	"Obtain IPV6 Servers automatically.":"IPV6 서버를 자동구성 합니다.",
	"Enable Automatic IPv6 Address Assignment":"IPv6 주소 자동 할당 사용",
	"Auto Detection":"자동 감지",
	"Auto Configuration (SLAAC/DHCPv6)":"자동 구성(SLAAC/DHCPv6)",
	"Automatic Time Confuguration":"자동 시간 구성",
	"Automatic Time Configuration":"자동 시간 구성",
	"Autoconfiguration Type":"자동 유형",
	"Obtain a DNS server address automatically":"자동으로 DNS 서버 주소 받기",
	"Obtain a DNS server address automatically or enter a specific DNS server address.":"자동으로 DNS 서버 주소 받거나 특정 DNS 서버 주소를 입력합니다.",
	"Click on any item in the diagram for more information.":"자세한 내용은 메뉴에서 해당 항목을 클릭합니다.",
	"Wrong password, please try again.":"잘못된 암호입니다. 다시 시도하십시오.",
	"Locked":"잠금",
	"Unlocked":"잠금 해제",
	"Please wait":"잠시 기다려주세요",
	"Your Device":"장치",
	"To access device management,click here.":"장치 관리에 액세스하려면 여기를 클릭하십시오.",
	"Device Admin Password":"장치 관리자 암호",
	"Router Advertisement Lifetime":"장치 알림 유지시간",
	"Device Name":"장치 이름",
	"DEVICE NAME SETUP":"장치 이름 설정",
	"Please enter a device name.":"장치 이름을 입력하십시오.",
	"The device is not connected to an uplink router, click &quot;Next&quot; to find available Wi-Fi networks.":"장치가 업링크 공유기에 연결되어 있지 않기 때문에 사용 가능한 Wi -Fi 네트워크를 찾을 수 없을 경우 \"다음\"을 클릭합니다.",
	"To access device management,":"장치 관리에 액세스하려면,",
	"To access device management, ":"장치 관리에 액세스하려면,",
	"Reboot The Device":"장치 재부팅",
	"Are you sure you want to restart the device?":"장치를 재시작하시겠습니까?",
	"Click on the pencil icon to give the device a name to make it easy to identify.":"장치명을 변경하려면 [연필] 아이콘을 클릭하여 주십시오.",
	"Click on the ":"장치명을 변경하려면 [연필] 아이콘을 클릭하여 주십시오.",
	"Choose a IPv4 provisioning mechanism to be used by the device.":"장치에서 사용 되는 IPv4의 프로비저닝 메커니즘을 선택합니다.",
	"Choose a IPv6 provisioning mechanism to be used by the device.":"장치에서 사용 되는 IPv6를 프로비저닝 메커니즘을 선택합니다.",
	"Device IP Address":"장치의 IP 주소",
	"Number of Device":"장치의 수",
	"Please plug one end of the Ethernet cable included with your device into the port labeled INTERNET on your device. Plug the other end of this cable into the Ethernet port on your DSL or cable broadband modem, and power cycle the modem.":"공유기의 인터넷 포트에 인터넷 선을 연결합니다.",
	"Please plug one end of the Ethernet cable included with your device into the port labeled INTERNET on your device. Plug the other end of this cable into the Ethernet port on yourDSL or cable broadband modem.":"공유기의 인터넷 포트에 인터넷 선을 연결합니다.",
	"Reboot":"재부팅",
	"Rebooting":"재부팅",
	"Rebooting....":"재부팅 중....",
	"Rebooting will disconnect any active internet sessions.":"재부팅 되면 모든 활성 인터넷 ​​세션이 끊어집니다.",
	"Retry":"재시도",
	"Save":"저장",
	"Before Save mydlink, the Admin Password of DIR-508L can not be blank.":"저장하기 전에, DIR-508L의 관리자 암호는 비워 둘 수 없습니다.,",
	"Sent":"전송",
	"Sent (Tx)":"전송 (TX)",
	"Sent (TX)":"전송 (TX)",
	"Transmission Power":"전송 전력",
	"Please enter your e-mail account name.":"이메일의 계정 이름을 입력 해주세요.",
	"E-mail Settings":"이메일 설정",
	"Please enter your e-mail password.":"이메일 암호를 입력하십시오.",
	"Please enter an e-mail address.":"이메일 주소를 입력 해주십시오.",
	"Please enter your e-mail address and mydlink password.":"이메일 주소와 mydlink 암호를 입력하십시오.",
	"The e-mail address and password combination is incorrect. Please try again.":"이메일 주소와 암호 조합이 잘못되었습니다. 다시 시도해주세요.",
	"On Log Full":"전체 로그",
	"Dial-up Number":"전화 번호",
	"Dial-up Number ":"전화 번호",
	"Dial-up Number:(optional)":"전화 번호 : (선택 사항)",
	"Please enter a prefix length.":"prefix 길이를 입력하십시오.",
	"Information: Your browser is not support HTML5, please upgrade your browser.":"정보 : 귀하의 브라우저가 HTML5를 지원하지 않습니다, ​​브라우저를 업그레이드 해주세요.",
	"Static Network":"고정 네트워크",
	"Remove":"제거",
	"Limited Connection":"제한된 연결",
	"terms and conditions.":"이용 약관",
	"Address Mode":"주소 모드",
	"ADDRESS AUTOCONFIGURATION SETTINGS":"주소 자동 설정",
	"Host":"호스트",
	"Medium":"중간",
	"Extender":"확장기",
	"Status":"사용",
	"Direct Links":"직접 링크",
	"Secondary IPv6 DNS Address":"서브 IPv6의 DNS 서버",
	"Note: If you are using a PPPoE connection, you will need to remove or disable any PPPoE client software running on your computers.":"참고 : PPPoE 방식인 경우, 윈도우 상에 별도의 접속 프로그램이나 광대역 연결이 설정되어 있을 수 있습니다. 공유기 설정전에 해당 프로그램을 삭제하여 주십시오.",
	"Browse":"찾아보기",
	"Browse ":"찾아보기 ",
	"Channel Width":"채널 폭",
	"System":"시스템",
	"Time Out":"시간 체크 아웃",
	"Sec":"초",
	"seconds":"초",
	"Second(s)":"초",
	"Seconds...":"초 ...",
	"Total Kbit(s)":"총 Kbit(s)",
	"Total Space":"총 공간",
	"Total Byte(s)":"총 바이트",
	"Total Packets":"총 패킷",
	"Using up to 32 characters":"최대 32 자까지 사용",
	"Maximum Idle Time":"최대 유휴 시간",
	"Min":"분",
	"Append":"추가",
	"Congratulations":"축하합니다.",
	"Please enter a source network IP address.":"출발지 네트워크 IP 주소를 입력하여 주십시오.",
	"Cancel":"취소",
	"Clear":"갱신",
	"DENY computers access to ONLY these sites":"해당 사이트에 컴퓨터들이 엑세스 할 수 없도록 거부합니다",
	"Computer Name":"컴퓨터 이름",
	"ALLOW computers access to ONLY these sites":"해당 사이트만 컴퓨터에 대한 액세스를 허용",
	"Cable/xDSL Broadband Modem":"케이블 / XDSL 광대역 모뎀",
	"Cable Status":"케이블 연결 상태",
	"Saturday":"토요일",
	"Statistics":"통계",
	"Features":"기능",
	"Upload File":"파일 업로드",
	"Save Settings To File":"파일로 설정 저장",
	"Restore Configuration From File":"파일로 구성 복원",
	"Restore Settings From File":"파일로 설정을 복원",
	"Select File":"파일 선택",
	"Please select a file":"파일을 선택하세요",
	"Firmware Imformation":"펌웨어 정보",
	"Firmware Information":"펌웨어 정보",
	"Please do not close the browser while the firmware is being downloaded!":"펌웨어 다운로드 중에는 본 화면을 종료하지 말아 주십시오!",
	"Firmware Version":"펌웨어 버전",
	"Upgrade Firmware":"펌웨어 업그레이드",
	"Firmware Upgrade success!":"펌웨어 업그레이드가 완료되었습니다.",
	"Firmware Upgrade failed!":"펌웨어 업그레이드에 실패하였습니다.",
	"Do not power off the router until the firmware upgrade is complete!":"펌웨어 업그레이드가 완료 될 때까지 공유기의 전원을 끄지 마십시오!",
	"Do not close the page or power off the service until the Firmware Upgrade is complete!":"펌웨어 업그레이드가 완료 될 때까지 전원을 끄거나 이 화면을 닫지 마십시오!",
	"Do not power off the device until the Firmware Upgrade is complete!":"펌웨어 업그레이드가 완료 될 때까지 장치의 전원을 끄지 마십시오!",
	"Firmware Uploading":"펌웨어 업로드 중",
	"Uploading Firmware":"펌웨어 업로드",
	"Edit":"편집",
	"Please enter a port number.":"포트 번호를 입력하십시오.",
	"Please enter a port range.":"포트 범위를 입력하십시오.",
	"Port Forwarding":"포트 포워딩",
	"Port Forwarding is used to open ports in your router and to redirect traffic to those ports to a specific device on your network. This may be needed for specific applications, games, or services. You can enter individual ports (80, 68, 888), port ranges (100-150), or in a mixed format (1020-5000, 689).":"포트 포워딩은 공유기에서 포트를 열고 사용자의 네트워크에 구성 된 특정 장치에서 사용하는 포트로 트래픽을 통과 시켜주는데 사용됩니다. 이 기능은 특정 응용 프로그램, 게임 또는 서비스에 필요할 수 있습니다. 설정은 개별 포트(80, 68, 888), 포트 범위(100-150), 또는 혼합 형식(1020-5000, 689)으로 입력 할 수 있습니다.",


	"Bandwidth": "대역폭",
	"Uplink Speed(Mbps)": "업 링크 속도 (Mbps)",
	"Downlink Speed(Mbps)": "다운 링크 속도 (Mbps)",


	"Your router helps share a single IP address assigned by your ISP among several clients in your home. Port forwarding allows traffic requests from a specified application to be directed to a specified client inside.":"포트 포워딩은 공유기에서 포트를 열고 사용자의 네트워크에 구성 된 특정 장치에서 사용하는 포트로 트래픽을 통과 시켜주는데 사용됩니다. 이 기능은 특정 응용 프로그램, 게임 또는 서비스에 필요할 수 있습니다. 설정은 개별 포트(80, 68, 888), 포트 범위(100-150), 또는 혼합 형식(1020-5000, 689)으로 입력 할 수 있습니다.",
	"Folder":"폴더",
	"Create Folder":"폴더 만들기",
	"Select Folder":"폴더 선택",
	"Please enter a folder name":"폴더 이름을 입력하십시오",
	"Protocol":"프로토콜",
	"Protocol Number":"프로토콜 번호",
	"Profile List":"프로필 목록",
	"Profile Name":"프로필 이름",
	"Profile Name ":"프로필 이름",
	"Add Profile":"프로필 추가",
	"Add Profile ":"프로필 추가",
	"Hardware Version":"하드웨어 버전",
	"Day":"일",
	"All Day":"하루종일",
	"Assigned Prefix":"Prefix 할당",
	"Total":"합계",
	"Total KByte(s)":"총 KBytes(s)",
	"Hotspot":"핫스팟",
	"Hotspot ":"핫스팟",
	"Hotspot Network":"핫스팟 네트워크",
	"Hotspot Network Name(SSID)":"핫스팟 네트워크 이름 (SSID)",
	"Hotspot Network Name(SSID) ":"핫스팟 네트워크 이름 (SSID)",
	"Hotspot Name (SSID)":"핫스팟 이름 (SSID)",
	"Hotspot Client":"핫스팟 클라이언트",
	"Always Broadcast":"항상 Broadcast",
	"Always on":"항상 켜짐",
	"Always-on":"항상 켜짐",
	"Please enter a value":"해당 값을 입력하여 주십시오",
	"This schedule cannot be deleted because it is being used by another feature.":"해당 스케줄 규칙이 다른 기능에 적용되어 있어 삭제할 수 없습니다.",
	"Release":"해제",
	"Release IP Address":"IP 주소 연결 해제",
	"Please enter a matrix.":"matrix값을 입력하십시오.",
	"Please enter a Metric.":"Metric을 입력하십시오.",
	"Permission":"허가",
	"Enable Hub and Spoke Mode":"Hub&Spoke 모드 사용",
	"Allowed":"허용",
	"CURRENT IPv6 ULA SETTINGS":"현재 IPv6 ULA 설정",
	"Current ULA Prefix":"현재 ULA Prefix",
	"Current Status":"현재 상태",
	"Current Language Pack":"현재 언어 팩",
	"Current Firmware Date":"현재 펌웨어 날짜",
	"Current Firmware Version":"현재 펌웨어 버전",
	"Host Name":"호스트 이름",
	"Please enter a host name.":"호스트명을 입력하여 주십시오.",
	"Mixed 802.11a and 802.11n":"802.11a and 802.11n 혼용",
	"Home":"홈",
	"Tuesday":"화요일",
	"Checking....,":"확인중 ....",
	"Give Your Extended Wi-Fi Network(SSID) a Name":"확장 된 Wi-Fi 네트워크 (SSID )이름을 지정",
	"Extended Wi-Fi Network Name":"확장 된 Wi-Fi 네트워크 이름",
	"Extended Wi-Fi Network Name(SSID)":"확장 된 Wi-Fi 네트워크 이름 ( SSID)",
	"Give Your Extended Wi-Fi Network a Password":"확장 된 Wi-Fi 네트워크암호를 제공 ",
	"Extended Wi-Fi":"확장 된 Wi-Fi",
	"Extended Wi-Fi Password":"확장 된 Wi-Fi 패스워드",
	"PLEASE ENTER THE SETTINGS FOR THE EXTENDED NETWORK":"확장 된 네트워크 에 대한 설정을 입력하십시오",
	"Use the same Wi-Fi Network Name for the Extended Network.":"확장 된 네트워크를 위해 동일한 Wi-Fi 네트워크 이름을 사용합니다.",
	"Welcome":"환영합니다",
	"Wi-Fi 2.4GHZ":"Wi-Fi 2.4GHz",
	"Guest Zone 2.4GHZ":"게스트 존 2.4GHz",
	"Guest Zone 5GHZ":"게스트 존 5GHz",
	"Smart Connect":"스마트 연결",
	"Primary 5GHz":"기본 5GHz",
	"Secondary 5GHz":"보조 5GHz",
	"5GHz Low Band Guest Zone":"5Ghz 하위채널 게스트 존",
	"5GHz High Band Guest Zone":"5Ghz 상위채널 게스트 존",
	"5GHz Low Band Wi-Fi Name (SSID)":"5Ghz 하위채널 무선 이름(SSID)",
	"5GHz High Band Wi-Fi Name (SSID)":"5Ghz 상위채널 무선 이름(SSID)",
	"Guest Zone 5GHz Secondary ":"5GHz 보조 게스트 존",
	"Interface is not ready, please check again. ":"인터페이스가 아직 준비되지 않았습니다. 다시 체크 해 주십시오.",
	"IP Address (Reserved)":"IP 주소 (예약 됨)",
	"terms and conditions. ":"이용 약관",
	"The selected profile does not connect to Internet. Please recheck the configuration of the profile. ":"선택한 프로필이 인터넷과 연결이 되지 않습니다. 프로필 파일을 다시 확인 해주십시오.",
	"The selected profile is not configured. ":"선택한 프로필은 올바른 구성이 아닙니다.",
	"Wi-Fi 5GHz Secondary ":"보조 Wi-Fi 5GHz",
	"It will take effect after reconnecting":"재연결 후 접속 됩니다.",
	"can't be broadcast address":"브로드캐스트 주소가 아닙니다.",
	"can't be network address":"네트워크 주소가 아닙니다.",
	"WAN Gateway IP address":"WAN 게이트웨이 IP 주소",
	"must be within the WAN subnet.":"WAN 서브넷은 반드시 같아야합니다.",
	"SSID is required.":"SSID가 반드시 필요합니다.",
	"The SSID contains invalid characters. Please check it.":"SSID 입력이 올바르지 않습니다. 다시 확인 해 주십시오.",
	"The Wireless Security Password must be at least 8 characters long.":"무선 보안 패스워드는 반드시 8자리 이상으로 입력해야 합니다.",
	"The password should not have space at the beginning or the end.":"암호는 8자 이상 중에 공란(space)은 입력 할 수 없습니다.",
	"The WPA key must be exactly 8 hexadecimal digits long (0-9, A-F).":"WPA 패스워드는 만드시 8자리 이상에 A-Z, 0-9 문자로 입력해야 합니다.",
	"Invalid WPA key. Please choose a WPA key containing exactly 8 hexadecimal characters.":"잘못 된 WPA 키입니다. WPA 키는 8자리 이상 입력 되어야 합니다.",
	"Congratulations, you are now connected to the Internet.":"축하합니다. 인터넷에 접속되었습니다.",
	"Complete Installation":"인스톨 완료",
	"CABLE DISCONNECTED FROM INTERNET PORT":"인터넷 포트에 케이블 연결이 끊어졌습니다.",
	"Please make sure the cable between the ADSL/cable modem and the router is properly connected.":"ADSL/cable 모뎀과 공유기에 랜케이블을 올바르게 연결해 주십시오.",
	"Please check that the hardware is properly connected and configured (refer to the Quick Installation Guide for details) and click \"Try Again\".":"하드웨어가 정상적으로 연결 되었는지 확인 및 설정 후,(빠른 인스톨 가이드를 참고하세요.) \"다시 시도\"를 클릭해 주십시오.",
	"PPPoE user name or password is incorrect.":"PPPoE의 사용자명 또는 패스워드가 맞지 않습니다.",
	"*User name and password are case-sensitive. Please ensure that Caps Lock is off, then click \"Previous\", re-enter the PPPoE user name and password, and click \"Connect\". ":"사용자명과 패스워드가 올바르지 않습니다. Caps Lock을 꺼주신 후, \"이전\" 버튼을 눌러 되돌아가신 후에 PPPoE 설정의 사용자명과 패스워드를 입력하시고 \"연결\" 버튼을 눌러 주시기 바랍니다.",
	"*Please check your Internet account information or contact your Internet service provider for your PPPoE details, then click \"Previous\", re-enter the PPPoE user name and password, and click \"Connect\". ":"사용 중인 인터넷 계정 정보 또는 PPPoE 계정 정보를 확인 하시고, \"이전\" 버튼을 눌러 되돌아가신 후에 PPPoE 설정의 사용자명과 패스워드를 입력하시고 \"연결\" 버튼을 눌러 주시기 바랍니다.",
	"CONNECTING TO THE INTERNET":"인터넷 연결중",
	"Specify your internet speed provided by your ISP; for example 10Mbps Upload, 20 Mbps download. You can measure your uplink and downlink speed with a speed test service on the internet.":"고객님의 인터넷 서비스 공급자를 통해 인터넷 속도를 확인 할 수 있습니다.(예, 10Mbps 업로드, 20Mbps 다운로드) 인터넷의 속도 테스트 서비스를 통해 업링크/다운링크 속도를 확인 할 수 있습니다.",
	"Uplink Speed(Mbps): ":"업링크 속도(Mbps): ",
	"Downlink Speed(Mbps): ":"다운링크 속도(Mbps): ",
	"Drag the device cards above to the Priority boxes below.":"아래의 Priority 상자에 위의 장치 카드를 드래그합니다.",
	"Below is a summary of your Wi-Fi security and device password settings. Please make a note of your settings and click \"Next\".":"하단의 내용은 Wi-Fi 설정 및 관리자 암호 설정에 대한 내용입니다. 해당 내용을 메모해 두시면, 잊어버릴 경우 확인이 쉽습니다.",
	
	"Congratulations, your device has been configured. You can now connect to your Wi-Fi network by using the new Wi-Fi Network Name and Password you created.":"장치 구성이 완료 되었습니다. 이제 새로 만든 Wi-Fi 네트워크 이름(SSID)과 비밀번호를 사용하여 Wi-Fi 네트워크에 연결할 수 있습니다.",
	"Admin Password": "로그인 비밀번호",
	"The Router IP Address is belong to the lease pool of DHCP server.": "DHCP 범위에 공유기의 IP는 입력 할 수 없습니다.",

	"err_required": "IP 주소를 입력하십시오.",
	"err_email": "전자 메일 주소를 입력 해주십시오.",
	"err_email_AccountName": "전자 메일 계정 이름을 입력 해주세요.",
	"err_email_Password": "전자 메일 암호를 입력하십시오.",
	"err_ssid": "Wi-Fi 이름 (SSID)을 입력하십시오.",
	"err_ip": "IP 주소를 입력하십시오.",
	"err_subnet_Mask": "서브넷 마스크를 입력하십시오.",
	"err_device_Name": "장치 이름을 입력하십시오.",
	"err_dlna_Name": "귀하의 DLNA 미디어 서버의 이름을 입력하십시오.",
	"err_port": "포트 번호를 입력하십시오.",
	"err_rule_Name": "이 규칙에 대한 이름을 입력 해주세요.",
	"err_ip_Range": "IP 주소 범위를 입력하십시오.",
	"err_port_Range": "포트 범위를 입력하십시오.",
	"err_address_CheckRange": "유효한 IP 주소 범위를 입력하십시오. (예 : 1.1.1.1-1.1.1.2)",
	"err_port_CheckRange": "유효한 포트 범위를 입력하십시오. (예 : 1000-1001)",
	"err_port_Check": "유효한 포트 번호를 입력하십시오.",
	"err_netmask": "넷 마스크를 입력하십시오.",
	"err_gateway_Address": "게이트웨이 주소를 입력 해주십시오.",
	"err_matrix": "행렬을 입력하십시오.",
	"err_netmask_Check": "유효한 넷 마스크를 입력하십시오. (예 : 255.255.255.0)",
	"err_gateway_AddressCheck": "유효한 게이트웨이 주소를 입력 해주십시오. (예 : 192.168.0.1)",
	"err_destinationIP": "대상 네트워크 IP 주소를 입력하십시오.",
	"err_prefix_Length": "접두사 길이를 입력하십시오.",
	"err_ipv6address_Check": "유효한 IPv6의 주소를 입력 해주십시오. (예 : 2001 :: 1)",
	"err_ipv6networkaddress_Check": "유효한 대상 네트워크의 IP 주소를 입력하십시오. (예 : 2001::)",
	"err_smtp": "SMTP 서버 주소를 입력 해주십시오.",
	"err_address_Check": "유효한 IP 주소를 입력 해주십시오. (예 : 192.168.0.1)",
	"err_address_CheckAllRange": "유효한 IP 주소를 입력 해주십시오. (예 : 255.255.255.0)",
	"err_check_UserName": "이름을 입력하세요.",
	"err_check_Password": "비밀번호를 입력하세요.",
	"err_email_Check": "사용할 이메일 주소를 입력하여 주십시오.",
	"err_host_Name": "호스트명을 입력하여 주십시오.",
	"err_sourceIP": "출발지 네트워크 IP 주소를 입력하여 주십시오.",
	"err_ipv6address_CheckRange": "사용할 IPv6 주소 범위를 입력하여 주십시오. (예, 2001::1-2001::2)",
	"err_password_WEPCheck": "비밀번호를 13 자리로 입력하여 주십시오",
	"err_password_WPACheck": "비밀번호를 8 ~ 63 자리로 입력하여 주십시오",
	"err_check_DeviceAdminPassword": "비밀번호를 6 ~ 15 자리로 입력하여 주십시오",
	"err_check_IllegalChar": "사용하실 수 없는 문자가 입력되어 있습니다",
	"err_hex_Range": "0 ~ FF 사이의 값으로 입력하여 주십시오",
	"err_range_Compare": "끝 주소가 시작 주소보다 커야 합니다",
	"err_number": "해당 값을 입력하여 주십시오",
	"err_ipv6": "IPv6 주소를 입력하여 주십시오.",
	"err_ipv6_PPPoE_Type": "IPv4 연결 방식이 PPPoE 로 설정되어 있어야 합니다",
	"err_ipv6_DsLite_Type": "당신은 인터넷에 액세스하는 대신 'DS-Lite'가 아닌 다른 IPv4의 인터넷 연결 모드를 선택해야합니다.",
	"err_wan_lan_conflict": "LAN 서브넷과 WAN 서브넷 충돌.",
	"err_Check_Mac": "Please enter a valid MAC address.",
	"err_mac_conflict": "The MAC address has existed.",

	"Unused":"사용 안함",
	"IPTV Port Setting":"IPTV 포트 설정",
	"Portal Page Redirect": "웹사이트 리다이렉션",
	"Router Mode": "공유기 모드",
	"Repeater Mode": "리피터 모드",
	"coexistence": "HT20/40 자동 전환",
	"Always": "항상",
	"VPN(PPTP) Mode": "VPN(PPTP) 서버",
	"Encryption": "암호화",
	"VPN account": "VPN 계정",
	"VPN password": "VPN 비밀번호",
	"Indicated IP address": "IP 주소",
	"Add": "생성",
	"(Most 5 sets)": "(최대 5개 생성 가능)",
	"Enable": "활성화",
	"IP address": "IP 주소",
	"state":"상태",
	
	"Features": "특징",
	"Device Mode": "장치 모드",
	"Bridge Mode": "브리지 모드",
	"The device is changing to bridge mode.": "장치가 브리지 모드로 변경되었습니다.",
	"The device is changing to router mode.": "장치는 공유기 모드로 변경되었습니다.",
	"Station": "스테이션",
	"Wireless Network Name": "무선 네트워크 이름(SSID)",
	"Security": "보안",
	"Scan": "검색",
	"Your changes are being saved.": "변경 사항을 저장하고 있습니다.",
	
	"Policy": "정책",
	"Lease time": "갱신 시간",
	"Website Link for Redirect": "웹사이트 링크 주소 입력",
	"Wireless Band": "무선 밴드",
	"A virtual private network (VPN) is a private network that interconnects remote netwoks through primarily public communication infrastructures such as the Internet.": "VPN (가상 사설망)은 인터넷과 같은 주로 공인IP를 통한 원격 네트워크를 상호 연결하여 개인 네트워크로 통신 할 수 있는 기능입니다.",
	"Disconnected": "연결 끊김",
	"Connected": "연결 됨",
	"(Seconds)": "(초)",
	"Bandwidth": "대역폭",
	"Uplink Speed(Mbps)": "업 링크 속도(Mbps)",
	"Downlink Speed(Mbps)": "다운 링크 속도(Mbps)",
	
	"Status": "상태",
	"Status:": "상태:",
	"Status1:":"상태:",
	"Status2": "상태",
	
	"Wi-Fi Channel:": "무선 채널",
	"Wi-Fi Channel1:": "Wi-Fi 채널",
	"COPYRIGHT": "COPYRIGHT &copy; 2015 D-Link"
	
	

}
