#!/bin/sh /etc/rc.common
# Copyright (C) 2007 OpenWrt.org
. /etc/functions.sh
include /lib/config

START=60

boot() {

chkv6=$(cat /etc/config/nework | grep ipv6 | grep 1)

[ -n "$chkv6" ] && {
j=0
while [ "$j" != 150 ]; do
     for i in "br-lan" 1 2 3 4
     do	
	if [ "$i" == "br-lan" ] ;then
	    vlanIFNAME=$i
	else
	    vlanIFNAME=$(uci get network.wan$i.bind_LAN)
	fi   
        [ -n "$vlanIFNAME" ] && {  	
	lan_prefix=$(ifconfig $vlanIFNAME | awk '/Global/{print $3}')
        }
	[ -n "$lan_prefix" ] && break
     done

     [ -n "$lan_prefix" ] && {
           /etc/init.d/radvd restart & 
           break          
     } 
     j=$(($j+1)) 
     sleep 2
done
} &


}

stop() { 
	return 0	
}

start() {
    ## This shell script is IPv6 Only
    chkv6=$(uci get network.wan.ipv6)
    [ -n "$chkv6" -a "$chkv6" == "1" ] && {
        config_load "default_lan_radvd"
        
        uci set dhcp6c.basic.default_write_prefix="1"
        uci set dhcp6c.basic.intfGrp_write_prefix="0"
        uci commit dhcp6c
        
        /etc/init.d/radvd restart
    }
}


